BINARY := secretd
PKG := ./cmd/secretd

# Workspace siblings that go.mod `replace`s with local paths. docker-prep copies
# them into the build context because a Docker build cannot reach outside it.
KIT_SRC ?= ../maintainerd-kit
SDK_SRC ?= ../maintainerd-sdk

# Docker image coordinates for a local build. Releases publish maintainerd/secret;
# this default keeps a local build clearly distinguishable from a published one.
IMAGE ?= maintainerd-secret
TAG ?= dev

.PHONY: build run tidy fmt vet test test-race cover test-cover check sqlc \
        proto proto-lint proto-breaking lint-proto staticcheck lint licenses \
        docker-prep docker-build docker-clean clean

build:
	go build -o bin/$(BINARY) $(PKG)

run:
	go run $(PKG)

tidy:
	go mod tidy

fmt:
	gofmt -w .

vet:
	go vet ./...

test:
	go test ./...

# The suite as CI runs it: race detector, no test cache.
test-race:
	go test ./... -count=1 -race

cover:
	go test -cover ./...

# Unit tests plus an HTML coverage report.
test-cover:
	go test ./... -count=1 -coverprofile=coverage.out
	go tool cover -html=coverage.out -o coverage.html
	@echo "Coverage report written to coverage.html"

# staticcheck reads staticcheck.conf at the repo root — the same check set the
# other maintainerd Go repos use.
staticcheck:
	staticcheck ./...

lint: vet staticcheck

# check is the full local gate, matching what CI enforces.
check: fmt vet staticcheck test
	@test -z "$$(gofmt -l .)" || (echo "gofmt found unformatted files:"; gofmt -l .; exit 1)

# sqlc regenerates internal/storage from migrations/*.sql + internal/storage/queries/*.sql.
# The migrations are the schema source of truth, so a column added there and a column
# the Go code believes in cannot drift apart.
sqlc:
	sqlc generate

# buf.yaml at the repo root is a v2 workspace declaring `modules: [{path: proto}]`,
# so every buf command runs from here.
proto:
	buf generate

proto-lint:
	buf lint

# Compares the contracts against origin/main. Requires a fetched origin/main
# (CI checks out with fetch-depth: 0 for exactly this).
proto-breaking:
	buf breaking --against '.git#branch=origin/main'

# Retained alias — proto-lint is the name CI and the sibling repos use.
lint-proto: proto-lint

# Check dependency licenses (fail on forbidden/restricted) and regenerate
# THIRD_PARTY_NOTICES.md. Apache-2.0 project: GPL/AGPL/LGPL must not be linked.
licenses:
	go install github.com/google/go-licenses@latest
	go-licenses check ./... --disallowed_types=forbidden,restricted
	@printf '# Third-Party Notices\n\nGenerated by `make licenses` (github.com/google/go-licenses). See NOTICE for project copyright.\n\n' > THIRD_PARTY_NOTICES.md
	go-licenses report ./... 2>/dev/null | sort >> THIRD_PARTY_NOTICES.md
	@echo "Third-party notices written to THIRD_PARTY_NOTICES.md"

# --- Docker -----------------------------------------------------------------
# go.mod replaces github.com/maintainerd/{kit,sdk} with ../maintainerd-{kit,sdk}.
# A Docker build cannot see outside its context, so the siblings are copied into
# .deps/ first and the Dockerfile repoints the replaces at ./.deps/* internally —
# your worktree go.mod is never modified. CI does the same with actions/checkout.
docker-prep:
	@test -d "$(KIT_SRC)" || (echo "missing sibling: $(KIT_SRC)"; exit 1)
	@test -d "$(SDK_SRC)" || (echo "missing sibling: $(SDK_SRC)"; exit 1)
	@rm -rf .deps
	@mkdir -p .deps
	@cp -a "$(KIT_SRC)" .deps/kit
	@cp -a "$(SDK_SRC)" .deps/sdk
	@rm -rf .deps/kit/.git .deps/sdk/.git
	@echo "sibling modules staged in .deps/ (kit, sdk)"

docker-build: docker-prep
	docker build --build-arg VERSION=$(TAG) -t $(IMAGE):$(TAG) .

docker-clean:
	rm -rf .deps

clean: docker-clean
	rm -rf bin/
