// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: audit_log.sql

package storage

import (
	"context"
	"net/netip"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const allowAuditLogDelete = `-- name: AllowAuditLogDelete :exec
SELECT set_config('maintainerd.allow_audit_log_delete', $1, true)
`

func (q *Queries) AllowAuditLogDelete(ctx context.Context, setConfig string) error {
	_, err := q.db.Exec(ctx, allowAuditLogDelete, setConfig)
	return err
}

const appendAuditEvent = `-- name: AppendAuditEvent :one

INSERT INTO audit_log (
    tenant_id, actor_subject, actor_kind, action, resource_mrn,
    secret_id, version, outcome, reason, ip_address, user_agent, request_id, metadata
) VALUES (
    $1, $2, $3, $4, $5,
    $6, $7, $8, $9, $10, $11, $12, $13
)
RETURNING event_id, event_uuid, tenant_id, actor_subject, actor_kind, action, resource_mrn, secret_id, version, outcome, reason, ip_address, user_agent, request_id, metadata, created_at
`

type AppendAuditEventParams struct {
	TenantID     pgtype.Int8 `json:"tenant_id"`
	ActorSubject string      `json:"actor_subject"`
	ActorKind    string      `json:"actor_kind"`
	Action       string      `json:"action"`
	ResourceMrn  string      `json:"resource_mrn"`
	SecretID     pgtype.Int8 `json:"secret_id"`
	Version      pgtype.Int4 `json:"version"`
	Outcome      string      `json:"outcome"`
	Reason       string      `json:"reason"`
	IpAddress    *netip.Addr `json:"ip_address"`
	UserAgent    string      `json:"user_agent"`
	RequestID    string      `json:"request_id"`
	Metadata     []byte      `json:"metadata"`
}

// The access trail. Append-only: there is no UPDATE statement in this file, and
// there never should be — the trigger on the table would reject one anyway.
func (q *Queries) AppendAuditEvent(ctx context.Context, arg AppendAuditEventParams) (AuditLog, error) {
	row := q.db.QueryRow(ctx, appendAuditEvent,
		arg.TenantID,
		arg.ActorSubject,
		arg.ActorKind,
		arg.Action,
		arg.ResourceMrn,
		arg.SecretID,
		arg.Version,
		arg.Outcome,
		arg.Reason,
		arg.IpAddress,
		arg.UserAgent,
		arg.RequestID,
		arg.Metadata,
	)
	var i AuditLog
	err := row.Scan(
		&i.EventID,
		&i.EventUuid,
		&i.TenantID,
		&i.ActorSubject,
		&i.ActorKind,
		&i.Action,
		&i.ResourceMrn,
		&i.SecretID,
		&i.Version,
		&i.Outcome,
		&i.Reason,
		&i.IpAddress,
		&i.UserAgent,
		&i.RequestID,
		&i.Metadata,
		&i.CreatedAt,
	)
	return i, err
}

const countAuditEventsByTenant = `-- name: CountAuditEventsByTenant :one
SELECT count(*) FROM audit_log WHERE tenant_id = $1
`

func (q *Queries) CountAuditEventsByTenant(ctx context.Context, tenantID pgtype.Int8) (int64, error) {
	row := q.db.QueryRow(ctx, countAuditEventsByTenant, tenantID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteAuditEventsBefore = `-- name: DeleteAuditEventsBefore :execrows
DELETE FROM audit_log WHERE created_at < $1
`

func (q *Queries) DeleteAuditEventsBefore(ctx context.Context, createdAt time.Time) (int64, error) {
	result, err := q.db.Exec(ctx, deleteAuditEventsBefore, createdAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const listAuditEventsByActor = `-- name: ListAuditEventsByActor :many
SELECT event_id, event_uuid, tenant_id, actor_subject, actor_kind, action, resource_mrn, secret_id, version, outcome, reason, ip_address, user_agent, request_id, metadata, created_at FROM audit_log
WHERE actor_subject = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListAuditEventsByActorParams struct {
	ActorSubject string `json:"actor_subject"`
	Limit        int32  `json:"limit"`
	Offset       int32  `json:"offset"`
}

func (q *Queries) ListAuditEventsByActor(ctx context.Context, arg ListAuditEventsByActorParams) ([]AuditLog, error) {
	rows, err := q.db.Query(ctx, listAuditEventsByActor, arg.ActorSubject, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AuditLog{}
	for rows.Next() {
		var i AuditLog
		if err := rows.Scan(
			&i.EventID,
			&i.EventUuid,
			&i.TenantID,
			&i.ActorSubject,
			&i.ActorKind,
			&i.Action,
			&i.ResourceMrn,
			&i.SecretID,
			&i.Version,
			&i.Outcome,
			&i.Reason,
			&i.IpAddress,
			&i.UserAgent,
			&i.RequestID,
			&i.Metadata,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAuditEventsBySecret = `-- name: ListAuditEventsBySecret :many
SELECT event_id, event_uuid, tenant_id, actor_subject, actor_kind, action, resource_mrn, secret_id, version, outcome, reason, ip_address, user_agent, request_id, metadata, created_at FROM audit_log
WHERE secret_id = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListAuditEventsBySecretParams struct {
	SecretID pgtype.Int8 `json:"secret_id"`
	Limit    int32       `json:"limit"`
	Offset   int32       `json:"offset"`
}

func (q *Queries) ListAuditEventsBySecret(ctx context.Context, arg ListAuditEventsBySecretParams) ([]AuditLog, error) {
	rows, err := q.db.Query(ctx, listAuditEventsBySecret, arg.SecretID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AuditLog{}
	for rows.Next() {
		var i AuditLog
		if err := rows.Scan(
			&i.EventID,
			&i.EventUuid,
			&i.TenantID,
			&i.ActorSubject,
			&i.ActorKind,
			&i.Action,
			&i.ResourceMrn,
			&i.SecretID,
			&i.Version,
			&i.Outcome,
			&i.Reason,
			&i.IpAddress,
			&i.UserAgent,
			&i.RequestID,
			&i.Metadata,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAuditEventsByTenant = `-- name: ListAuditEventsByTenant :many
SELECT event_id, event_uuid, tenant_id, actor_subject, actor_kind, action, resource_mrn, secret_id, version, outcome, reason, ip_address, user_agent, request_id, metadata, created_at FROM audit_log
WHERE tenant_id = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListAuditEventsByTenantParams struct {
	TenantID pgtype.Int8 `json:"tenant_id"`
	Limit    int32       `json:"limit"`
	Offset   int32       `json:"offset"`
}

func (q *Queries) ListAuditEventsByTenant(ctx context.Context, arg ListAuditEventsByTenantParams) ([]AuditLog, error) {
	rows, err := q.db.Query(ctx, listAuditEventsByTenant, arg.TenantID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AuditLog{}
	for rows.Next() {
		var i AuditLog
		if err := rows.Scan(
			&i.EventID,
			&i.EventUuid,
			&i.TenantID,
			&i.ActorSubject,
			&i.ActorKind,
			&i.Action,
			&i.ResourceMrn,
			&i.SecretID,
			&i.Version,
			&i.Outcome,
			&i.Reason,
			&i.IpAddress,
			&i.UserAgent,
			&i.RequestID,
			&i.Metadata,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
