// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: dynamic.sql

package storage

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countDynamicLeasesByRole = `-- name: CountDynamicLeasesByRole :one
SELECT count(*) FROM dynamic_leases
WHERE tenant_id = $1 AND role_id = $2
`

type CountDynamicLeasesByRoleParams struct {
	TenantID int64 `json:"tenant_id"`
	RoleID   int64 `json:"role_id"`
}

func (q *Queries) CountDynamicLeasesByRole(ctx context.Context, arg CountDynamicLeasesByRoleParams) (int64, error) {
	row := q.db.QueryRow(ctx, countDynamicLeasesByRole, arg.TenantID, arg.RoleID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countDynamicRolesByProject = `-- name: CountDynamicRolesByProject :one
SELECT count(*) FROM dynamic_roles
WHERE tenant_id = $1 AND project_id = $2 AND deleted_at IS NULL
`

type CountDynamicRolesByProjectParams struct {
	TenantID  int64 `json:"tenant_id"`
	ProjectID int64 `json:"project_id"`
}

func (q *Queries) CountDynamicRolesByProject(ctx context.Context, arg CountDynamicRolesByProjectParams) (int64, error) {
	row := q.db.QueryRow(ctx, countDynamicRolesByProject, arg.TenantID, arg.ProjectID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countLiveDynamicLeasesByRole = `-- name: CountLiveDynamicLeasesByRole :one
SELECT count(*) FROM dynamic_leases WHERE role_id = $1 AND revoked_at IS NULL
`

// CountLiveDynamicLeasesByRole is the delete guard: a role config with outstanding
// credentials must not be soft-deleted out from under them, because the revocation
// template lives on the config and deleting it would strand every issued account.
func (q *Queries) CountLiveDynamicLeasesByRole(ctx context.Context, roleID int64) (int64, error) {
	row := q.db.QueryRow(ctx, countLiveDynamicLeasesByRole, roleID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createDynamicLease = `-- name: CreateDynamicLease :one
INSERT INTO dynamic_leases (
    role_id, tenant_id, db_role_name, resource_mrn,
    requester, requester_kind, expires_at, metadata
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING lease_id, lease_uuid, role_id, tenant_id, db_role_name, resource_mrn, requester, requester_kind, issued_at, expires_at, revoked_at, revoke_reason, revoke_error, revoke_attempts, metadata, created_at, updated_at
`

type CreateDynamicLeaseParams struct {
	RoleID        int64     `json:"role_id"`
	TenantID      int64     `json:"tenant_id"`
	DbRoleName    string    `json:"db_role_name"`
	ResourceMrn   string    `json:"resource_mrn"`
	Requester     string    `json:"requester"`
	RequesterKind string    `json:"requester_kind"`
	ExpiresAt     time.Time `json:"expires_at"`
	Metadata      []byte    `json:"metadata"`
}

// CreateDynamicLease records an issued credential. It is written in the SAME
// transaction that runs the creation SQL against the target database, so there is no
// window in which a database role exists with no lease row demanding its revocation.
func (q *Queries) CreateDynamicLease(ctx context.Context, arg CreateDynamicLeaseParams) (DynamicLease, error) {
	row := q.db.QueryRow(ctx, createDynamicLease,
		arg.RoleID,
		arg.TenantID,
		arg.DbRoleName,
		arg.ResourceMrn,
		arg.Requester,
		arg.RequesterKind,
		arg.ExpiresAt,
		arg.Metadata,
	)
	var i DynamicLease
	err := row.Scan(
		&i.LeaseID,
		&i.LeaseUuid,
		&i.RoleID,
		&i.TenantID,
		&i.DbRoleName,
		&i.ResourceMrn,
		&i.Requester,
		&i.RequesterKind,
		&i.IssuedAt,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.RevokeReason,
		&i.RevokeError,
		&i.RevokeAttempts,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createDynamicRole = `-- name: CreateDynamicRole :one

INSERT INTO dynamic_roles (
    tenant_id, project_id, name, description, dsn_secret_ref,
    creation_sql, revocation_sql, default_ttl_seconds, max_ttl_seconds,
    role_name_prefix, status, metadata
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12)
RETURNING role_id, role_uuid, tenant_id, project_id, name, description, dsn_secret_ref, creation_sql, revocation_sql, default_ttl_seconds, max_ttl_seconds, role_name_prefix, status, metadata, created_at, updated_at, deleted_at
`

type CreateDynamicRoleParams struct {
	TenantID          int64  `json:"tenant_id"`
	ProjectID         int64  `json:"project_id"`
	Name              string `json:"name"`
	Description       string `json:"description"`
	DsnSecretRef      string `json:"dsn_secret_ref"`
	CreationSql       string `json:"creation_sql"`
	RevocationSql     string `json:"revocation_sql"`
	DefaultTtlSeconds int32  `json:"default_ttl_seconds"`
	MaxTtlSeconds     int32  `json:"max_ttl_seconds"`
	RoleNamePrefix    string `json:"role_name_prefix"`
	Status            string `json:"status"`
	Metadata          []byte `json:"metadata"`
}

// Dynamic secrets: the role CONFIGURATION an operator registers, and the LEASES
// issued against it.
//
// TENANT SCOPING IS IN THE QUERY, not in the service — the same rule the secret
// queries follow, for the same reason: a WHERE clause that is part of the generated
// function's signature cannot be forgotten, whereas a service-layer check is one
// early return away from leaking.
//
// NOTE WHAT NO QUERY IN THIS FILE DOES: none of them writes or reads a generated
// password, because there is no column to hold one. The credential is returned to
// the caller once, in the issue response, and revocation needs only a role name.
func (q *Queries) CreateDynamicRole(ctx context.Context, arg CreateDynamicRoleParams) (DynamicRole, error) {
	row := q.db.QueryRow(ctx, createDynamicRole,
		arg.TenantID,
		arg.ProjectID,
		arg.Name,
		arg.Description,
		arg.DsnSecretRef,
		arg.CreationSql,
		arg.RevocationSql,
		arg.DefaultTtlSeconds,
		arg.MaxTtlSeconds,
		arg.RoleNamePrefix,
		arg.Status,
		arg.Metadata,
	)
	var i DynamicRole
	err := row.Scan(
		&i.RoleID,
		&i.RoleUuid,
		&i.TenantID,
		&i.ProjectID,
		&i.Name,
		&i.Description,
		&i.DsnSecretRef,
		&i.CreationSql,
		&i.RevocationSql,
		&i.DefaultTtlSeconds,
		&i.MaxTtlSeconds,
		&i.RoleNamePrefix,
		&i.Status,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getDynamicLeaseByUUID = `-- name: GetDynamicLeaseByUUID :one
SELECT lease_id, lease_uuid, role_id, tenant_id, db_role_name, resource_mrn, requester, requester_kind, issued_at, expires_at, revoked_at, revoke_reason, revoke_error, revoke_attempts, metadata, created_at, updated_at FROM dynamic_leases
WHERE tenant_id = $1 AND lease_uuid = $2
`

type GetDynamicLeaseByUUIDParams struct {
	TenantID  int64     `json:"tenant_id"`
	LeaseUuid uuid.UUID `json:"lease_uuid"`
}

func (q *Queries) GetDynamicLeaseByUUID(ctx context.Context, arg GetDynamicLeaseByUUIDParams) (DynamicLease, error) {
	row := q.db.QueryRow(ctx, getDynamicLeaseByUUID, arg.TenantID, arg.LeaseUuid)
	var i DynamicLease
	err := row.Scan(
		&i.LeaseID,
		&i.LeaseUuid,
		&i.RoleID,
		&i.TenantID,
		&i.DbRoleName,
		&i.ResourceMrn,
		&i.Requester,
		&i.RequesterKind,
		&i.IssuedAt,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.RevokeReason,
		&i.RevokeError,
		&i.RevokeAttempts,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getDynamicRoleByID = `-- name: GetDynamicRoleByID :one
SELECT role_id, role_uuid, tenant_id, project_id, name, description, dsn_secret_ref, creation_sql, revocation_sql, default_ttl_seconds, max_ttl_seconds, role_name_prefix, status, metadata, created_at, updated_at, deleted_at FROM dynamic_roles WHERE role_id = $1
`

// GetDynamicRoleByID resolves the config a lease was issued against, for the reaper —
// which starts from a lease row and needs the revocation template. It is NOT
// tenant-scoped because a lease row's role_id was itself reached through a
// tenant-scoped read (or, for the reaper, through a query that carries the tenant
// alongside), and a background sweep has no caller tenant to scope by. The revocation
// it performs is bounded by the lease row, not by the caller.
func (q *Queries) GetDynamicRoleByID(ctx context.Context, roleID int64) (DynamicRole, error) {
	row := q.db.QueryRow(ctx, getDynamicRoleByID, roleID)
	var i DynamicRole
	err := row.Scan(
		&i.RoleID,
		&i.RoleUuid,
		&i.TenantID,
		&i.ProjectID,
		&i.Name,
		&i.Description,
		&i.DsnSecretRef,
		&i.CreationSql,
		&i.RevocationSql,
		&i.DefaultTtlSeconds,
		&i.MaxTtlSeconds,
		&i.RoleNamePrefix,
		&i.Status,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getDynamicRoleByName = `-- name: GetDynamicRoleByName :one
SELECT role_id, role_uuid, tenant_id, project_id, name, description, dsn_secret_ref, creation_sql, revocation_sql, default_ttl_seconds, max_ttl_seconds, role_name_prefix, status, metadata, created_at, updated_at, deleted_at FROM dynamic_roles
WHERE tenant_id = $1
  AND project_id = $2
  AND name = $3
  AND deleted_at IS NULL
`

type GetDynamicRoleByNameParams struct {
	TenantID  int64  `json:"tenant_id"`
	ProjectID int64  `json:"project_id"`
	Name      string `json:"name"`
}

func (q *Queries) GetDynamicRoleByName(ctx context.Context, arg GetDynamicRoleByNameParams) (DynamicRole, error) {
	row := q.db.QueryRow(ctx, getDynamicRoleByName, arg.TenantID, arg.ProjectID, arg.Name)
	var i DynamicRole
	err := row.Scan(
		&i.RoleID,
		&i.RoleUuid,
		&i.TenantID,
		&i.ProjectID,
		&i.Name,
		&i.Description,
		&i.DsnSecretRef,
		&i.CreationSql,
		&i.RevocationSql,
		&i.DefaultTtlSeconds,
		&i.MaxTtlSeconds,
		&i.RoleNamePrefix,
		&i.Status,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getDynamicRoleByUUID = `-- name: GetDynamicRoleByUUID :one
SELECT role_id, role_uuid, tenant_id, project_id, name, description, dsn_secret_ref, creation_sql, revocation_sql, default_ttl_seconds, max_ttl_seconds, role_name_prefix, status, metadata, created_at, updated_at, deleted_at FROM dynamic_roles
WHERE tenant_id = $1
  AND role_uuid = $2
  AND deleted_at IS NULL
`

type GetDynamicRoleByUUIDParams struct {
	TenantID int64     `json:"tenant_id"`
	RoleUuid uuid.UUID `json:"role_uuid"`
}

func (q *Queries) GetDynamicRoleByUUID(ctx context.Context, arg GetDynamicRoleByUUIDParams) (DynamicRole, error) {
	row := q.db.QueryRow(ctx, getDynamicRoleByUUID, arg.TenantID, arg.RoleUuid)
	var i DynamicRole
	err := row.Scan(
		&i.RoleID,
		&i.RoleUuid,
		&i.TenantID,
		&i.ProjectID,
		&i.Name,
		&i.Description,
		&i.DsnSecretRef,
		&i.CreationSql,
		&i.RevocationSql,
		&i.DefaultTtlSeconds,
		&i.MaxTtlSeconds,
		&i.RoleNamePrefix,
		&i.Status,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listDynamicLeasesByRole = `-- name: ListDynamicLeasesByRole :many
SELECT lease_id, lease_uuid, role_id, tenant_id, db_role_name, resource_mrn,
       requester, requester_kind, issued_at, expires_at, revoked_at,
       revoke_reason, revoke_error, revoke_attempts
FROM dynamic_leases
WHERE tenant_id = $1 AND role_id = $2
ORDER BY created_at DESC
LIMIT $4 OFFSET $3
`

type ListDynamicLeasesByRoleParams struct {
	TenantID  int64 `json:"tenant_id"`
	RoleID    int64 `json:"role_id"`
	RowOffset int32 `json:"row_offset"`
	RowLimit  int32 `json:"row_limit"`
}

type ListDynamicLeasesByRoleRow struct {
	LeaseID        int64              `json:"lease_id"`
	LeaseUuid      uuid.UUID          `json:"lease_uuid"`
	RoleID         int64              `json:"role_id"`
	TenantID       int64              `json:"tenant_id"`
	DbRoleName     string             `json:"db_role_name"`
	ResourceMrn    string             `json:"resource_mrn"`
	Requester      string             `json:"requester"`
	RequesterKind  string             `json:"requester_kind"`
	IssuedAt       time.Time          `json:"issued_at"`
	ExpiresAt      time.Time          `json:"expires_at"`
	RevokedAt      pgtype.Timestamptz `json:"revoked_at"`
	RevokeReason   string             `json:"revoke_reason"`
	RevokeError    string             `json:"revoke_error"`
	RevokeAttempts int32              `json:"revoke_attempts"`
}

func (q *Queries) ListDynamicLeasesByRole(ctx context.Context, arg ListDynamicLeasesByRoleParams) ([]ListDynamicLeasesByRoleRow, error) {
	rows, err := q.db.Query(ctx, listDynamicLeasesByRole,
		arg.TenantID,
		arg.RoleID,
		arg.RowOffset,
		arg.RowLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListDynamicLeasesByRoleRow{}
	for rows.Next() {
		var i ListDynamicLeasesByRoleRow
		if err := rows.Scan(
			&i.LeaseID,
			&i.LeaseUuid,
			&i.RoleID,
			&i.TenantID,
			&i.DbRoleName,
			&i.ResourceMrn,
			&i.Requester,
			&i.RequesterKind,
			&i.IssuedAt,
			&i.ExpiresAt,
			&i.RevokedAt,
			&i.RevokeReason,
			&i.RevokeError,
			&i.RevokeAttempts,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDynamicRoleMetaByProject = `-- name: ListDynamicRoleMetaByProject :many
SELECT role_uuid, project_id, name, description, dsn_secret_ref,
       default_ttl_seconds, max_ttl_seconds, role_name_prefix, status,
       created_at, updated_at
FROM dynamic_roles
WHERE tenant_id = $1
  AND project_id = $2
  AND deleted_at IS NULL
ORDER BY name
LIMIT $4 OFFSET $3
`

type ListDynamicRoleMetaByProjectParams struct {
	TenantID  int64 `json:"tenant_id"`
	ProjectID int64 `json:"project_id"`
	RowOffset int32 `json:"row_offset"`
	RowLimit  int32 `json:"row_limit"`
}

type ListDynamicRoleMetaByProjectRow struct {
	RoleUuid          uuid.UUID `json:"role_uuid"`
	ProjectID         int64     `json:"project_id"`
	Name              string    `json:"name"`
	Description       string    `json:"description"`
	DsnSecretRef      string    `json:"dsn_secret_ref"`
	DefaultTtlSeconds int32     `json:"default_ttl_seconds"`
	MaxTtlSeconds     int32     `json:"max_ttl_seconds"`
	RoleNamePrefix    string    `json:"role_name_prefix"`
	Status            string    `json:"status"`
	CreatedAt         time.Time `json:"created_at"`
	UpdatedAt         time.Time `json:"updated_at"`
}

// ListDynamicRoleMetaByProject is the API/console read. The select list omits nothing
// sensitive — there is nothing sensitive to omit, because the DSN is a REFERENCE
// rather than a credential — but it does omit the SQL templates, which are long and
// belong on the detail read rather than in every page of a listing.
func (q *Queries) ListDynamicRoleMetaByProject(ctx context.Context, arg ListDynamicRoleMetaByProjectParams) ([]ListDynamicRoleMetaByProjectRow, error) {
	rows, err := q.db.Query(ctx, listDynamicRoleMetaByProject,
		arg.TenantID,
		arg.ProjectID,
		arg.RowOffset,
		arg.RowLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListDynamicRoleMetaByProjectRow{}
	for rows.Next() {
		var i ListDynamicRoleMetaByProjectRow
		if err := rows.Scan(
			&i.RoleUuid,
			&i.ProjectID,
			&i.Name,
			&i.Description,
			&i.DsnSecretRef,
			&i.DefaultTtlSeconds,
			&i.MaxTtlSeconds,
			&i.RoleNamePrefix,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listExpiredDynamicLeases = `-- name: ListExpiredDynamicLeases :many
SELECT lease_id, lease_uuid, role_id, tenant_id, db_role_name, resource_mrn,
       requester, requester_kind, expires_at, revoke_attempts
FROM dynamic_leases
WHERE revoked_at IS NULL AND expires_at <= now()
ORDER BY expires_at
LIMIT $1
`

type ListExpiredDynamicLeasesRow struct {
	LeaseID        int64     `json:"lease_id"`
	LeaseUuid      uuid.UUID `json:"lease_uuid"`
	RoleID         int64     `json:"role_id"`
	TenantID       int64     `json:"tenant_id"`
	DbRoleName     string    `json:"db_role_name"`
	ResourceMrn    string    `json:"resource_mrn"`
	Requester      string    `json:"requester"`
	RequesterKind  string    `json:"requester_kind"`
	ExpiresAt      time.Time `json:"expires_at"`
	RevokeAttempts int32     `json:"revoke_attempts"`
}

// ListExpiredDynamicLeases is THE REAPER'S QUERY, and the reason expiry does not
// depend on the creation template having included VALID UNTIL. now() is the
// database's, not the caller's: a skewed process clock must not be able to reap early
// or late.
//
// Ordered by expires_at so the longest-overdue account is dropped first, and limited
// so one pass cannot hold a connection to every target database at once.
func (q *Queries) ListExpiredDynamicLeases(ctx context.Context, rowLimit int32) ([]ListExpiredDynamicLeasesRow, error) {
	rows, err := q.db.Query(ctx, listExpiredDynamicLeases, rowLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListExpiredDynamicLeasesRow{}
	for rows.Next() {
		var i ListExpiredDynamicLeasesRow
		if err := rows.Scan(
			&i.LeaseID,
			&i.LeaseUuid,
			&i.RoleID,
			&i.TenantID,
			&i.DbRoleName,
			&i.ResourceMrn,
			&i.Requester,
			&i.RequesterKind,
			&i.ExpiresAt,
			&i.RevokeAttempts,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markDynamicLeaseRevoked = `-- name: MarkDynamicLeaseRevoked :execrows
UPDATE dynamic_leases
SET revoked_at      = now(),
    revoke_reason   = $1,
    revoke_error    = '',
    revoke_attempts = revoke_attempts + 1,
    updated_at      = now()
WHERE lease_id = $2 AND revoked_at IS NULL
`

type MarkDynamicLeaseRevokedParams struct {
	RevokeReason string `json:"revoke_reason"`
	LeaseID      int64  `json:"lease_id"`
}

// MarkDynamicLeaseRevoked closes a lease. Guarded on revoked_at IS NULL so a
// concurrent reaper pass and an explicit revoke cannot both claim the same lease —
// whichever loses gets zero rows and stops, rather than running DROP ROLE twice.
func (q *Queries) MarkDynamicLeaseRevoked(ctx context.Context, arg MarkDynamicLeaseRevokedParams) (int64, error) {
	result, err := q.db.Exec(ctx, markDynamicLeaseRevoked, arg.RevokeReason, arg.LeaseID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const recordDynamicLeaseRevokeFailure = `-- name: RecordDynamicLeaseRevokeFailure :execrows
UPDATE dynamic_leases
SET revoke_error    = $1,
    revoke_attempts = revoke_attempts + 1,
    updated_at      = now()
WHERE lease_id = $2 AND revoked_at IS NULL
`

type RecordDynamicLeaseRevokeFailureParams struct {
	RevokeError string `json:"revoke_error"`
	LeaseID     int64  `json:"lease_id"`
}

// RecordDynamicLeaseRevokeFailure leaves the lease OPEN on purpose. A revocation that
// the target database refused has not happened, and marking it revoked anyway would
// lose the only record that a live account needs dropping. The attempt count and the
// error are what an operator sees when a role has been orphaned by an outage.
func (q *Queries) RecordDynamicLeaseRevokeFailure(ctx context.Context, arg RecordDynamicLeaseRevokeFailureParams) (int64, error) {
	result, err := q.db.Exec(ctx, recordDynamicLeaseRevokeFailure, arg.RevokeError, arg.LeaseID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const softDeleteDynamicRole = `-- name: SoftDeleteDynamicRole :execrows
UPDATE dynamic_roles SET deleted_at = now(), updated_at = now()
WHERE tenant_id = $1
  AND role_uuid = $2
  AND deleted_at IS NULL
`

type SoftDeleteDynamicRoleParams struct {
	TenantID int64     `json:"tenant_id"`
	RoleUuid uuid.UUID `json:"role_uuid"`
}

func (q *Queries) SoftDeleteDynamicRole(ctx context.Context, arg SoftDeleteDynamicRoleParams) (int64, error) {
	result, err := q.db.Exec(ctx, softDeleteDynamicRole, arg.TenantID, arg.RoleUuid)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateDynamicRole = `-- name: UpdateDynamicRole :one
UPDATE dynamic_roles
SET description         = $1,
    dsn_secret_ref      = $2,
    creation_sql        = $3,
    revocation_sql      = $4,
    default_ttl_seconds = $5,
    max_ttl_seconds     = $6,
    status              = $7,
    updated_at          = now()
WHERE tenant_id = $8
  AND role_uuid = $9
  AND deleted_at IS NULL
RETURNING role_id, role_uuid, tenant_id, project_id, name, description, dsn_secret_ref, creation_sql, revocation_sql, default_ttl_seconds, max_ttl_seconds, role_name_prefix, status, metadata, created_at, updated_at, deleted_at
`

type UpdateDynamicRoleParams struct {
	Description       string    `json:"description"`
	DsnSecretRef      string    `json:"dsn_secret_ref"`
	CreationSql       string    `json:"creation_sql"`
	RevocationSql     string    `json:"revocation_sql"`
	DefaultTtlSeconds int32     `json:"default_ttl_seconds"`
	MaxTtlSeconds     int32     `json:"max_ttl_seconds"`
	Status            string    `json:"status"`
	TenantID          int64     `json:"tenant_id"`
	RoleUuid          uuid.UUID `json:"role_uuid"`
}

func (q *Queries) UpdateDynamicRole(ctx context.Context, arg UpdateDynamicRoleParams) (DynamicRole, error) {
	row := q.db.QueryRow(ctx, updateDynamicRole,
		arg.Description,
		arg.DsnSecretRef,
		arg.CreationSql,
		arg.RevocationSql,
		arg.DefaultTtlSeconds,
		arg.MaxTtlSeconds,
		arg.Status,
		arg.TenantID,
		arg.RoleUuid,
	)
	var i DynamicRole
	err := row.Scan(
		&i.RoleID,
		&i.RoleUuid,
		&i.TenantID,
		&i.ProjectID,
		&i.Name,
		&i.Description,
		&i.DsnSecretRef,
		&i.CreationSql,
		&i.RevocationSql,
		&i.DefaultTtlSeconds,
		&i.MaxTtlSeconds,
		&i.RoleNamePrefix,
		&i.Status,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
