// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: environment.sql

package storage

import (
	"context"

	"github.com/google/uuid"
)

const createEnvironment = `-- name: CreateEnvironment :one

INSERT INTO environments (project_id, name, slug, description, position, status, metadata)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING environment_id, environment_uuid, project_id, name, slug, description, position, status, metadata, created_by, updated_by, created_at, updated_at, deleted_at
`

type CreateEnvironmentParams struct {
	ProjectID   int64  `json:"project_id"`
	Name        string `json:"name"`
	Slug        string `json:"slug"`
	Description string `json:"description"`
	Position    int32  `json:"position"`
	Status      string `json:"status"`
	Metadata    []byte `json:"metadata"`
}

// Environments. The table has no tenant_id column (it hangs off a project), so
// tenant scoping is applied with a project subquery rather than a join — that
// keeps the select list a plain `*` (so sqlc returns the Environment struct) while
// still putting the tenant boundary inside the SQL.
func (q *Queries) CreateEnvironment(ctx context.Context, arg CreateEnvironmentParams) (Environment, error) {
	row := q.db.QueryRow(ctx, createEnvironment,
		arg.ProjectID,
		arg.Name,
		arg.Slug,
		arg.Description,
		arg.Position,
		arg.Status,
		arg.Metadata,
	)
	var i Environment
	err := row.Scan(
		&i.EnvironmentID,
		&i.EnvironmentUuid,
		&i.ProjectID,
		&i.Name,
		&i.Slug,
		&i.Description,
		&i.Position,
		&i.Status,
		&i.Metadata,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getEnvironmentByID = `-- name: GetEnvironmentByID :one
SELECT environment_id, environment_uuid, project_id, name, slug, description, position, status, metadata, created_by, updated_by, created_at, updated_at, deleted_at FROM environments
WHERE environment_id = $1
  AND deleted_at IS NULL
  AND project_id IN (SELECT p.project_id FROM projects p WHERE p.tenant_id = $2 AND p.deleted_at IS NULL)
`

type GetEnvironmentByIDParams struct {
	EnvironmentID int64 `json:"environment_id"`
	TenantID      int64 `json:"tenant_id"`
}

func (q *Queries) GetEnvironmentByID(ctx context.Context, arg GetEnvironmentByIDParams) (Environment, error) {
	row := q.db.QueryRow(ctx, getEnvironmentByID, arg.EnvironmentID, arg.TenantID)
	var i Environment
	err := row.Scan(
		&i.EnvironmentID,
		&i.EnvironmentUuid,
		&i.ProjectID,
		&i.Name,
		&i.Slug,
		&i.Description,
		&i.Position,
		&i.Status,
		&i.Metadata,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getEnvironmentBySlug = `-- name: GetEnvironmentBySlug :one
SELECT e.environment_id, e.environment_uuid, e.project_id, e.name, e.slug, e.description, e.position, e.status, e.metadata, e.created_by, e.updated_by, e.created_at, e.updated_at, e.deleted_at FROM environments e
WHERE e.project_id = $1
  AND e.slug = $2
  AND deleted_at IS NULL
  AND project_id IN (SELECT p.project_id FROM projects p WHERE p.tenant_id = $3 AND p.deleted_at IS NULL)
`

type GetEnvironmentBySlugParams struct {
	ProjectID int64  `json:"project_id"`
	Slug      string `json:"slug"`
	TenantID  int64  `json:"tenant_id"`
}

func (q *Queries) GetEnvironmentBySlug(ctx context.Context, arg GetEnvironmentBySlugParams) (Environment, error) {
	row := q.db.QueryRow(ctx, getEnvironmentBySlug, arg.ProjectID, arg.Slug, arg.TenantID)
	var i Environment
	err := row.Scan(
		&i.EnvironmentID,
		&i.EnvironmentUuid,
		&i.ProjectID,
		&i.Name,
		&i.Slug,
		&i.Description,
		&i.Position,
		&i.Status,
		&i.Metadata,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getEnvironmentByUUID = `-- name: GetEnvironmentByUUID :one
SELECT environment_id, environment_uuid, project_id, name, slug, description, position, status, metadata, created_by, updated_by, created_at, updated_at, deleted_at FROM environments
WHERE environment_uuid = $1
  AND deleted_at IS NULL
  AND project_id IN (SELECT p.project_id FROM projects p WHERE p.tenant_id = $2 AND p.deleted_at IS NULL)
`

type GetEnvironmentByUUIDParams struct {
	EnvironmentUuid uuid.UUID `json:"environment_uuid"`
	TenantID        int64     `json:"tenant_id"`
}

func (q *Queries) GetEnvironmentByUUID(ctx context.Context, arg GetEnvironmentByUUIDParams) (Environment, error) {
	row := q.db.QueryRow(ctx, getEnvironmentByUUID, arg.EnvironmentUuid, arg.TenantID)
	var i Environment
	err := row.Scan(
		&i.EnvironmentID,
		&i.EnvironmentUuid,
		&i.ProjectID,
		&i.Name,
		&i.Slug,
		&i.Description,
		&i.Position,
		&i.Status,
		&i.Metadata,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listEnvironmentsByProject = `-- name: ListEnvironmentsByProject :many
SELECT e.environment_id, e.environment_uuid, e.project_id, e.name, e.slug, e.description, e.position, e.status, e.metadata, e.created_by, e.updated_by, e.created_at, e.updated_at, e.deleted_at FROM environments e
WHERE e.project_id = $1
  AND e.deleted_at IS NULL
  AND project_id IN (SELECT p.project_id FROM projects p WHERE p.tenant_id = $2 AND p.deleted_at IS NULL)
ORDER BY position, slug
`

type ListEnvironmentsByProjectParams struct {
	ProjectID int64 `json:"project_id"`
	TenantID  int64 `json:"tenant_id"`
}

func (q *Queries) ListEnvironmentsByProject(ctx context.Context, arg ListEnvironmentsByProjectParams) ([]Environment, error) {
	rows, err := q.db.Query(ctx, listEnvironmentsByProject, arg.ProjectID, arg.TenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Environment{}
	for rows.Next() {
		var i Environment
		if err := rows.Scan(
			&i.EnvironmentID,
			&i.EnvironmentUuid,
			&i.ProjectID,
			&i.Name,
			&i.Slug,
			&i.Description,
			&i.Position,
			&i.Status,
			&i.Metadata,
			&i.CreatedBy,
			&i.UpdatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteEnvironment = `-- name: SoftDeleteEnvironment :execrows
UPDATE environments SET deleted_at = now(), updated_at = now()
WHERE environment_uuid = $1
  AND deleted_at IS NULL
  AND project_id IN (SELECT p.project_id FROM projects p WHERE p.tenant_id = $2 AND p.deleted_at IS NULL)
`

type SoftDeleteEnvironmentParams struct {
	EnvironmentUuid uuid.UUID `json:"environment_uuid"`
	TenantID        int64     `json:"tenant_id"`
}

func (q *Queries) SoftDeleteEnvironment(ctx context.Context, arg SoftDeleteEnvironmentParams) (int64, error) {
	result, err := q.db.Exec(ctx, softDeleteEnvironment, arg.EnvironmentUuid, arg.TenantID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateEnvironment = `-- name: UpdateEnvironment :one
UPDATE environments
SET name        = $1,
    description = $2,
    position    = $3,
    status      = $4,
    metadata    = $5,
    updated_at  = now()
WHERE environment_uuid = $6
  AND deleted_at IS NULL
  AND project_id IN (SELECT p.project_id FROM projects p WHERE p.tenant_id = $7 AND p.deleted_at IS NULL)
RETURNING environment_id, environment_uuid, project_id, name, slug, description, position, status, metadata, created_by, updated_by, created_at, updated_at, deleted_at
`

type UpdateEnvironmentParams struct {
	Name            string    `json:"name"`
	Description     string    `json:"description"`
	Position        int32     `json:"position"`
	Status          string    `json:"status"`
	Metadata        []byte    `json:"metadata"`
	EnvironmentUuid uuid.UUID `json:"environment_uuid"`
	TenantID        int64     `json:"tenant_id"`
}

func (q *Queries) UpdateEnvironment(ctx context.Context, arg UpdateEnvironmentParams) (Environment, error) {
	row := q.db.QueryRow(ctx, updateEnvironment,
		arg.Name,
		arg.Description,
		arg.Position,
		arg.Status,
		arg.Metadata,
		arg.EnvironmentUuid,
		arg.TenantID,
	)
	var i Environment
	err := row.Scan(
		&i.EnvironmentID,
		&i.EnvironmentUuid,
		&i.ProjectID,
		&i.Name,
		&i.Slug,
		&i.Description,
		&i.Position,
		&i.Status,
		&i.Metadata,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
