// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: folder.sql

package storage

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countFoldersInSubtree = `-- name: CountFoldersInSubtree :one
SELECT count(*) FROM folders
WHERE environment_id = $1
  AND (path = $2 OR path LIKE $3)
  AND deleted_at IS NULL
`

type CountFoldersInSubtreeParams struct {
	EnvironmentID int64  `json:"environment_id"`
	Path          string `json:"path"`
	PathPattern   string `json:"path_pattern"`
}

func (q *Queries) CountFoldersInSubtree(ctx context.Context, arg CountFoldersInSubtreeParams) (int64, error) {
	row := q.db.QueryRow(ctx, countFoldersInSubtree, arg.EnvironmentID, arg.Path, arg.PathPattern)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createFolder = `-- name: CreateFolder :one

INSERT INTO folders (environment_id, parent_folder_id, name, path, metadata)
VALUES ($1, $2, $3, $4, $5)
RETURNING folder_id, folder_uuid, environment_id, parent_folder_id, name, path, metadata, created_by, updated_by, created_at, updated_at, deleted_at
`

type CreateFolderParams struct {
	EnvironmentID  int64       `json:"environment_id"`
	ParentFolderID pgtype.Int8 `json:"parent_folder_id"`
	Name           string      `json:"name"`
	Path           string      `json:"path"`
	Metadata       []byte      `json:"metadata"`
}

// Folders. Tenant scoping walks up through environments and projects in a
// subquery, for the same reason environment.sql does it that way.
//
// Subtree matching is always expressed as `path = @path OR path LIKE @path_pattern`
// with BOTH values supplied by the caller, rather than building the pattern in SQL
// with a CASE. That is deliberate: the root folder's path is '/', so the naive
// `path || '/%'` produces '//%' and matches none of its children. The Go side owns
// that edge case in one place (store.SubtreePattern) instead of repeating a CASE
// expression in every query, and the pattern stays a plain runtime constant so the
// text_pattern_ops index on (environment_id, path) is still a range scan.
func (q *Queries) CreateFolder(ctx context.Context, arg CreateFolderParams) (Folder, error) {
	row := q.db.QueryRow(ctx, createFolder,
		arg.EnvironmentID,
		arg.ParentFolderID,
		arg.Name,
		arg.Path,
		arg.Metadata,
	)
	var i Folder
	err := row.Scan(
		&i.FolderID,
		&i.FolderUuid,
		&i.EnvironmentID,
		&i.ParentFolderID,
		&i.Name,
		&i.Path,
		&i.Metadata,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getFolderByID = `-- name: GetFolderByID :one
SELECT folder_id, folder_uuid, environment_id, parent_folder_id, name, path, metadata, created_by, updated_by, created_at, updated_at, deleted_at FROM folders
WHERE folder_id = $1
  AND deleted_at IS NULL
  AND environment_id IN (
      SELECT e.environment_id FROM environments e
      JOIN projects p ON p.project_id = e.project_id
      WHERE p.tenant_id = $2 AND e.deleted_at IS NULL AND p.deleted_at IS NULL)
`

type GetFolderByIDParams struct {
	FolderID int64 `json:"folder_id"`
	TenantID int64 `json:"tenant_id"`
}

func (q *Queries) GetFolderByID(ctx context.Context, arg GetFolderByIDParams) (Folder, error) {
	row := q.db.QueryRow(ctx, getFolderByID, arg.FolderID, arg.TenantID)
	var i Folder
	err := row.Scan(
		&i.FolderID,
		&i.FolderUuid,
		&i.EnvironmentID,
		&i.ParentFolderID,
		&i.Name,
		&i.Path,
		&i.Metadata,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getFolderByPath = `-- name: GetFolderByPath :one
SELECT f.folder_id, f.folder_uuid, f.environment_id, f.parent_folder_id, f.name, f.path, f.metadata, f.created_by, f.updated_by, f.created_at, f.updated_at, f.deleted_at FROM folders f
WHERE f.environment_id = $1
  AND f.path = $2
  AND f.deleted_at IS NULL
  AND f.environment_id IN (
      SELECT e.environment_id FROM environments e
      JOIN projects p ON p.project_id = e.project_id
      WHERE p.tenant_id = $3 AND e.deleted_at IS NULL AND p.deleted_at IS NULL)
`

type GetFolderByPathParams struct {
	EnvironmentID int64  `json:"environment_id"`
	Path          string `json:"path"`
	TenantID      int64  `json:"tenant_id"`
}

func (q *Queries) GetFolderByPath(ctx context.Context, arg GetFolderByPathParams) (Folder, error) {
	row := q.db.QueryRow(ctx, getFolderByPath, arg.EnvironmentID, arg.Path, arg.TenantID)
	var i Folder
	err := row.Scan(
		&i.FolderID,
		&i.FolderUuid,
		&i.EnvironmentID,
		&i.ParentFolderID,
		&i.Name,
		&i.Path,
		&i.Metadata,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getFolderByUUID = `-- name: GetFolderByUUID :one
SELECT folder_id, folder_uuid, environment_id, parent_folder_id, name, path, metadata, created_by, updated_by, created_at, updated_at, deleted_at FROM folders
WHERE folder_uuid = $1
  AND deleted_at IS NULL
  AND environment_id IN (
      SELECT e.environment_id FROM environments e
      JOIN projects p ON p.project_id = e.project_id
      WHERE p.tenant_id = $2 AND e.deleted_at IS NULL AND p.deleted_at IS NULL)
`

type GetFolderByUUIDParams struct {
	FolderUuid uuid.UUID `json:"folder_uuid"`
	TenantID   int64     `json:"tenant_id"`
}

func (q *Queries) GetFolderByUUID(ctx context.Context, arg GetFolderByUUIDParams) (Folder, error) {
	row := q.db.QueryRow(ctx, getFolderByUUID, arg.FolderUuid, arg.TenantID)
	var i Folder
	err := row.Scan(
		&i.FolderID,
		&i.FolderUuid,
		&i.EnvironmentID,
		&i.ParentFolderID,
		&i.Name,
		&i.Path,
		&i.Metadata,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listFoldersBySubtree = `-- name: ListFoldersBySubtree :many
SELECT f.folder_id, f.folder_uuid, f.environment_id, f.parent_folder_id, f.name, f.path, f.metadata, f.created_by, f.updated_by, f.created_at, f.updated_at, f.deleted_at FROM folders f
WHERE f.environment_id = $1
  AND (f.path = $2 OR f.path LIKE $3)
  AND f.deleted_at IS NULL
  AND f.environment_id IN (
      SELECT e.environment_id FROM environments e
      JOIN projects p ON p.project_id = e.project_id
      WHERE p.tenant_id = $4 AND e.deleted_at IS NULL AND p.deleted_at IS NULL)
ORDER BY f.path
`

type ListFoldersBySubtreeParams struct {
	EnvironmentID int64  `json:"environment_id"`
	Path          string `json:"path"`
	PathPattern   string `json:"path_pattern"`
	TenantID      int64  `json:"tenant_id"`
}

func (q *Queries) ListFoldersBySubtree(ctx context.Context, arg ListFoldersBySubtreeParams) ([]Folder, error) {
	rows, err := q.db.Query(ctx, listFoldersBySubtree,
		arg.EnvironmentID,
		arg.Path,
		arg.PathPattern,
		arg.TenantID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Folder{}
	for rows.Next() {
		var i Folder
		if err := rows.Scan(
			&i.FolderID,
			&i.FolderUuid,
			&i.EnvironmentID,
			&i.ParentFolderID,
			&i.Name,
			&i.Path,
			&i.Metadata,
			&i.CreatedBy,
			&i.UpdatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const moveFolderSubtreePaths = `-- name: MoveFolderSubtreePaths :execrows
UPDATE folders
SET path = $1::text || substring(path FROM length($2::text) + 1),
    updated_at = now()
WHERE environment_id = $3
  AND (path = $2::text OR path LIKE $4)
  AND deleted_at IS NULL
`

type MoveFolderSubtreePathsParams struct {
	NewPath        string `json:"new_path"`
	OldPath        string `json:"old_path"`
	EnvironmentID  int64  `json:"environment_id"`
	OldPathPattern string `json:"old_path_pattern"`
}

// MoveFolderSubtreePaths rewrites the materialized paths of a moved subtree by
// prefix substitution: everything at or under old_path is re-rooted at new_path.
// substring(path FROM length(old_path) + 1) is the part of each descendant's path
// below the moved node, so '/db/primary' under a '/db' -> '/data' move becomes
// '/data' || '/primary'.
func (q *Queries) MoveFolderSubtreePaths(ctx context.Context, arg MoveFolderSubtreePathsParams) (int64, error) {
	result, err := q.db.Exec(ctx, moveFolderSubtreePaths,
		arg.NewPath,
		arg.OldPath,
		arg.EnvironmentID,
		arg.OldPathPattern,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const reparentFolder = `-- name: ReparentFolder :one
UPDATE folders
SET parent_folder_id = $1,
    name             = $2,
    path             = $3,
    updated_at       = now()
WHERE folder_id = $4 AND deleted_at IS NULL
RETURNING folder_id, folder_uuid, environment_id, parent_folder_id, name, path, metadata, created_by, updated_by, created_at, updated_at, deleted_at
`

type ReparentFolderParams struct {
	ParentFolderID pgtype.Int8 `json:"parent_folder_id"`
	Name           string      `json:"name"`
	Path           string      `json:"path"`
	FolderID       int64       `json:"folder_id"`
}

// ReparentFolder moves one folder node: its parent, its name and its own path.
// The subtree beneath it is rewritten separately by MoveFolderSubtreePaths, and
// both statements must run in the same transaction or the materialized paths would
// be observably inconsistent with parent_folder_id.
func (q *Queries) ReparentFolder(ctx context.Context, arg ReparentFolderParams) (Folder, error) {
	row := q.db.QueryRow(ctx, reparentFolder,
		arg.ParentFolderID,
		arg.Name,
		arg.Path,
		arg.FolderID,
	)
	var i Folder
	err := row.Scan(
		&i.FolderID,
		&i.FolderUuid,
		&i.EnvironmentID,
		&i.ParentFolderID,
		&i.Name,
		&i.Path,
		&i.Metadata,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const softDeleteFolderSubtree = `-- name: SoftDeleteFolderSubtree :execrows
UPDATE folders SET deleted_at = now(), updated_at = now()
WHERE environment_id = $1
  AND (path = $2 OR path LIKE $3)
  AND deleted_at IS NULL
`

type SoftDeleteFolderSubtreeParams struct {
	EnvironmentID int64  `json:"environment_id"`
	Path          string `json:"path"`
	PathPattern   string `json:"path_pattern"`
}

func (q *Queries) SoftDeleteFolderSubtree(ctx context.Context, arg SoftDeleteFolderSubtreeParams) (int64, error) {
	result, err := q.db.Exec(ctx, softDeleteFolderSubtree, arg.EnvironmentID, arg.Path, arg.PathPattern)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
