// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: project.sql

package storage

import (
	"context"

	"github.com/google/uuid"
)

const countProjectsByTenant = `-- name: CountProjectsByTenant :one
SELECT count(*) FROM projects WHERE tenant_id = $1 AND deleted_at IS NULL
`

func (q *Queries) CountProjectsByTenant(ctx context.Context, tenantID int64) (int64, error) {
	row := q.db.QueryRow(ctx, countProjectsByTenant, tenantID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createProject = `-- name: CreateProject :one

INSERT INTO projects (tenant_id, name, slug, description, status, metadata)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING project_id, project_uuid, tenant_id, name, slug, description, status, metadata, created_by, updated_by, created_at, updated_at, deleted_at
`

type CreateProjectParams struct {
	TenantID    int64  `json:"tenant_id"`
	Name        string `json:"name"`
	Slug        string `json:"slug"`
	Description string `json:"description"`
	Status      string `json:"status"`
	Metadata    []byte `json:"metadata"`
}

// Projects. Every read carries tenant_id in the WHERE clause — see the note in
// secret.sql on why tenant scoping lives in the query and not in the service.
func (q *Queries) CreateProject(ctx context.Context, arg CreateProjectParams) (Project, error) {
	row := q.db.QueryRow(ctx, createProject,
		arg.TenantID,
		arg.Name,
		arg.Slug,
		arg.Description,
		arg.Status,
		arg.Metadata,
	)
	var i Project
	err := row.Scan(
		&i.ProjectID,
		&i.ProjectUuid,
		&i.TenantID,
		&i.Name,
		&i.Slug,
		&i.Description,
		&i.Status,
		&i.Metadata,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getProjectByID = `-- name: GetProjectByID :one
SELECT project_id, project_uuid, tenant_id, name, slug, description, status, metadata, created_by, updated_by, created_at, updated_at, deleted_at FROM projects WHERE tenant_id = $1 AND project_id = $2 AND deleted_at IS NULL
`

type GetProjectByIDParams struct {
	TenantID  int64 `json:"tenant_id"`
	ProjectID int64 `json:"project_id"`
}

func (q *Queries) GetProjectByID(ctx context.Context, arg GetProjectByIDParams) (Project, error) {
	row := q.db.QueryRow(ctx, getProjectByID, arg.TenantID, arg.ProjectID)
	var i Project
	err := row.Scan(
		&i.ProjectID,
		&i.ProjectUuid,
		&i.TenantID,
		&i.Name,
		&i.Slug,
		&i.Description,
		&i.Status,
		&i.Metadata,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getProjectBySlug = `-- name: GetProjectBySlug :one
SELECT project_id, project_uuid, tenant_id, name, slug, description, status, metadata, created_by, updated_by, created_at, updated_at, deleted_at FROM projects WHERE tenant_id = $1 AND slug = $2 AND deleted_at IS NULL
`

type GetProjectBySlugParams struct {
	TenantID int64  `json:"tenant_id"`
	Slug     string `json:"slug"`
}

func (q *Queries) GetProjectBySlug(ctx context.Context, arg GetProjectBySlugParams) (Project, error) {
	row := q.db.QueryRow(ctx, getProjectBySlug, arg.TenantID, arg.Slug)
	var i Project
	err := row.Scan(
		&i.ProjectID,
		&i.ProjectUuid,
		&i.TenantID,
		&i.Name,
		&i.Slug,
		&i.Description,
		&i.Status,
		&i.Metadata,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getProjectByUUID = `-- name: GetProjectByUUID :one
SELECT project_id, project_uuid, tenant_id, name, slug, description, status, metadata, created_by, updated_by, created_at, updated_at, deleted_at FROM projects WHERE tenant_id = $1 AND project_uuid = $2 AND deleted_at IS NULL
`

type GetProjectByUUIDParams struct {
	TenantID    int64     `json:"tenant_id"`
	ProjectUuid uuid.UUID `json:"project_uuid"`
}

func (q *Queries) GetProjectByUUID(ctx context.Context, arg GetProjectByUUIDParams) (Project, error) {
	row := q.db.QueryRow(ctx, getProjectByUUID, arg.TenantID, arg.ProjectUuid)
	var i Project
	err := row.Scan(
		&i.ProjectID,
		&i.ProjectUuid,
		&i.TenantID,
		&i.Name,
		&i.Slug,
		&i.Description,
		&i.Status,
		&i.Metadata,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listProjectsByTenant = `-- name: ListProjectsByTenant :many
SELECT project_id, project_uuid, tenant_id, name, slug, description, status, metadata, created_by, updated_by, created_at, updated_at, deleted_at FROM projects
WHERE tenant_id = $1 AND deleted_at IS NULL
ORDER BY slug
LIMIT $2 OFFSET $3
`

type ListProjectsByTenantParams struct {
	TenantID int64 `json:"tenant_id"`
	Limit    int32 `json:"limit"`
	Offset   int32 `json:"offset"`
}

func (q *Queries) ListProjectsByTenant(ctx context.Context, arg ListProjectsByTenantParams) ([]Project, error) {
	rows, err := q.db.Query(ctx, listProjectsByTenant, arg.TenantID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Project{}
	for rows.Next() {
		var i Project
		if err := rows.Scan(
			&i.ProjectID,
			&i.ProjectUuid,
			&i.TenantID,
			&i.Name,
			&i.Slug,
			&i.Description,
			&i.Status,
			&i.Metadata,
			&i.CreatedBy,
			&i.UpdatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteProject = `-- name: SoftDeleteProject :execrows
UPDATE projects SET deleted_at = now(), updated_at = now()
WHERE tenant_id = $1 AND project_uuid = $2 AND deleted_at IS NULL
`

type SoftDeleteProjectParams struct {
	TenantID    int64     `json:"tenant_id"`
	ProjectUuid uuid.UUID `json:"project_uuid"`
}

func (q *Queries) SoftDeleteProject(ctx context.Context, arg SoftDeleteProjectParams) (int64, error) {
	result, err := q.db.Exec(ctx, softDeleteProject, arg.TenantID, arg.ProjectUuid)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateProject = `-- name: UpdateProject :one
UPDATE projects
SET name        = $1,
    description = $2,
    status      = $3,
    metadata    = $4,
    updated_at  = now()
WHERE tenant_id = $5 AND project_uuid = $6 AND deleted_at IS NULL
RETURNING project_id, project_uuid, tenant_id, name, slug, description, status, metadata, created_by, updated_by, created_at, updated_at, deleted_at
`

type UpdateProjectParams struct {
	Name        string    `json:"name"`
	Description string    `json:"description"`
	Status      string    `json:"status"`
	Metadata    []byte    `json:"metadata"`
	TenantID    int64     `json:"tenant_id"`
	ProjectUuid uuid.UUID `json:"project_uuid"`
}

func (q *Queries) UpdateProject(ctx context.Context, arg UpdateProjectParams) (Project, error) {
	row := q.db.QueryRow(ctx, updateProject,
		arg.Name,
		arg.Description,
		arg.Status,
		arg.Metadata,
		arg.TenantID,
		arg.ProjectUuid,
	)
	var i Project
	err := row.Scan(
		&i.ProjectID,
		&i.ProjectUuid,
		&i.TenantID,
		&i.Name,
		&i.Slug,
		&i.Description,
		&i.Status,
		&i.Metadata,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
