// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package storage

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	AllowAuditLogDelete(ctx context.Context, setConfig string) error
	// AllowSecretVersionDelete sets the transaction-local GUC the append-only trigger
	// checks. Valid reasons: 'retention', 'secret_destroy', 'tenant_delete'. is_local
	// is true, so the permission dies with the transaction and cannot leak into the
	// next statement on a pooled connection — which is exactly why it must be called
	// inside an explicit transaction to have any effect at all.
	AllowSecretVersionDelete(ctx context.Context, setConfig string) error
	AllowSecretVersionRewrap(ctx context.Context) error
	// The access trail. Append-only: there is no UPDATE statement in this file, and
	// there never should be — the trigger on the table would reject one anyway.
	AppendAuditEvent(ctx context.Context, arg AppendAuditEventParams) (AuditLog, error)
	// CompleteSetup is the one-shot itself. The `WHERE setup_state.completed_at IS
	// NULL` guard on the DO UPDATE branch is what makes it single-use: a second caller
	// matches the conflict, fails the guard, updates nothing, and gets NO ROW back —
	// which the service reads as "already complete". Two concurrent callers therefore
	// cannot both win, because the row lock taken by ON CONFLICT serializes them and
	// the loser sees the winner's completed_at.
	//
	// This is the fix for the prototype's in-memory lock, which reopened the setup
	// window on every process restart (and, with an empty bootstrap token, reopened it
	// unauthenticated).
	CompleteSetup(ctx context.Context, arg CompleteSetupParams) (SetupState, error)
	CountAuditEventsByTenant(ctx context.Context, tenantID pgtype.Int8) (int64, error)
	CountFoldersInSubtree(ctx context.Context, arg CountFoldersInSubtreeParams) (int64, error)
	CountProjectsByTenant(ctx context.Context, tenantID int64) (int64, error)
	CountSecretVersions(ctx context.Context, secretID int64) (int64, error)
	CountSecretsInSubtree(ctx context.Context, arg CountSecretsInSubtreeParams) (int64, error)
	CountTenants(ctx context.Context) (int64, error)
	// CountVersionsByKEK is the retirement proof: a root key may only be retired when
	// this returns zero.
	CountVersionsByKEK(ctx context.Context, kekID string) (int64, error)
	// Environments. The table has no tenant_id column (it hangs off a project), so
	// tenant scoping is applied with a project subquery rather than a join — that
	// keeps the select list a plain `*` (so sqlc returns the Environment struct) while
	// still putting the tenant boundary inside the SQL.
	CreateEnvironment(ctx context.Context, arg CreateEnvironmentParams) (Environment, error)
	// Folders. Tenant scoping walks up through environments and projects in a
	// subquery, for the same reason environment.sql does it that way.
	//
	// Subtree matching is always expressed as `path = @path OR path LIKE @path_pattern`
	// with BOTH values supplied by the caller, rather than building the pattern in SQL
	// with a CASE. That is deliberate: the root folder's path is '/', so the naive
	// `path || '/%'` produces '//%' and matches none of its children. The Go side owns
	// that edge case in one place (store.SubtreePattern) instead of repeating a CASE
	// expression in every query, and the pattern stays a plain runtime constant so the
	// text_pattern_ops index on (environment_id, path) is still a range scan.
	CreateFolder(ctx context.Context, arg CreateFolderParams) (Folder, error)
	// Projects. Every read carries tenant_id in the WHERE clause — see the note in
	// secret.sql on why tenant scoping lives in the query and not in the service.
	CreateProject(ctx context.Context, arg CreateProjectParams) (Project, error)
	// Secrets: identity and metadata. NO QUERY IN THIS FILE RETURNS A VALUE, because
	// the secrets table has no value column at all — payloads live only in
	// secret_versions (see secret_version.sql).
	//
	// TENANT SCOPING IS IN THE QUERY, NOT IN THE SERVICE. Every statement here
	// constrains tenant_id. That is the difference between "we remember to check" and
	// "it cannot happen": a service-layer check is one forgotten early-return away
	// from leaking, whereas a WHERE clause that is part of the generated function's
	// signature cannot be skipped — sqlc will not compile a call that omits the
	// parameter. This is also why tenant_id is denormalized onto secrets rather than
	// reached by joining up through project and environment.
	CreateSecret(ctx context.Context, arg CreateSecretParams) (Secret, error)
	// Secret versions: the encrypted payloads.
	//
	// These are the only queries in the repo that touch ciphertext, and every one of
	// them is reached through a secret row that was already resolved tenant-scoped
	// (secret.sql). secret_id is therefore a capability: holding one means the tenant
	// check has already happened. Versions carry no tenant_id of their own for the
	// same reason a bank note carries no account number.
	CreateSecretVersion(ctx context.Context, arg CreateSecretVersionParams) (SecretVersion, error)
	// The tenant mirror. Auth owns identity; these rows exist so every secret can be
	// keyed to a tenant with one indexed local read instead of a cross-service call.
	//
	// created_by / updated_by are left to their NULL defaults throughout this file.
	// This service has no users table — the authenticated principal is an Auth
	// subject string, and it is recorded where it belongs, in audit_log.actor_subject.
	// The BIGINT audit columns are kept for schema parity with core.
	CreateTenant(ctx context.Context, arg CreateTenantParams) (Tenant, error)
	DeleteAuditEventsBefore(ctx context.Context, createdAt time.Time) (int64, error)
	DeleteSecretVersion(ctx context.Context, versionID int64) (int64, error)
	// The durable one-shot setup lock.
	EnsureSetupState(ctx context.Context) error
	GetActiveRootKey(ctx context.Context) (RootKey, error)
	GetDeletedSecretByUUID(ctx context.Context, arg GetDeletedSecretByUUIDParams) (Secret, error)
	GetEnvironmentByID(ctx context.Context, arg GetEnvironmentByIDParams) (Environment, error)
	GetEnvironmentBySlug(ctx context.Context, arg GetEnvironmentBySlugParams) (Environment, error)
	GetEnvironmentByUUID(ctx context.Context, arg GetEnvironmentByUUIDParams) (Environment, error)
	GetFolderByID(ctx context.Context, arg GetFolderByIDParams) (Folder, error)
	GetFolderByPath(ctx context.Context, arg GetFolderByPathParams) (Folder, error)
	GetFolderByUUID(ctx context.Context, arg GetFolderByUUIDParams) (Folder, error)
	GetLatestSecretVersion(ctx context.Context, secretID int64) (SecretVersion, error)
	// GetLatestVersionChecksum answers "is this write actually a change?" without
	// decrypting anything, and without the root key being involved at all. That is the
	// whole reason checksum is a stored column.
	GetLatestVersionChecksum(ctx context.Context, secretID int64) (GetLatestVersionChecksumRow, error)
	GetProjectByID(ctx context.Context, arg GetProjectByIDParams) (Project, error)
	GetProjectBySlug(ctx context.Context, arg GetProjectBySlugParams) (Project, error)
	GetProjectByUUID(ctx context.Context, arg GetProjectByUUIDParams) (Project, error)
	GetRootKey(ctx context.Context, kekID string) (RootKey, error)
	GetSecretByAddress(ctx context.Context, arg GetSecretByAddressParams) (Secret, error)
	// GetSecretByAddressForUpdate takes a row lock for the write path. Two concurrent
	// writes to one secret must serialize: both would otherwise read the same
	// current_version, and the second would collide on uq_secret_versions_secret_version
	// (or worse, silently reuse a version number if that index were ever relaxed).
	GetSecretByAddressForUpdate(ctx context.Context, arg GetSecretByAddressForUpdateParams) (Secret, error)
	GetSecretByUUID(ctx context.Context, arg GetSecretByUUIDParams) (Secret, error)
	GetSecretVersion(ctx context.Context, arg GetSecretVersionParams) (SecretVersion, error)
	GetSetupState(ctx context.Context) (SetupState, error)
	GetTenantByAuthTenantUUID(ctx context.Context, authTenantUuid pgtype.UUID) (Tenant, error)
	GetTenantByID(ctx context.Context, tenantID int64) (Tenant, error)
	GetTenantByName(ctx context.Context, name string) (Tenant, error)
	GetTenantByUUID(ctx context.Context, tenantUuid uuid.UUID) (Tenant, error)
	// HardDeleteSecret is irreversible. The recovery-window guard is IN THE QUERY and
	// reads now() from the database rather than trusting a timestamp from the caller:
	// destruction inside the window would be unrecoverable data loss, so the check has
	// to hold even against a clock-skewed caller or a future code path that forgets
	// to look. Cascades into secret_versions, which requires the
	// maintainerd.allow_secret_version_delete GUC to be set to 'secret_destroy' in
	// the same transaction.
	HardDeleteSecret(ctx context.Context, arg HardDeleteSecretParams) (int64, error)
	ListAuditEventsByActor(ctx context.Context, arg ListAuditEventsByActorParams) ([]AuditLog, error)
	ListAuditEventsBySecret(ctx context.Context, arg ListAuditEventsBySecretParams) ([]AuditLog, error)
	ListAuditEventsByTenant(ctx context.Context, arg ListAuditEventsByTenantParams) ([]AuditLog, error)
	// ListDeletedSecretMeta is the recovery-window view: what can still be restored,
	// and until when. Metadata only, same rule as the live listing.
	ListDeletedSecretMeta(ctx context.Context, arg ListDeletedSecretMetaParams) ([]ListDeletedSecretMetaRow, error)
	ListEnvironmentsByProject(ctx context.Context, arg ListEnvironmentsByProjectParams) ([]Environment, error)
	ListFoldersBySubtree(ctx context.Context, arg ListFoldersBySubtreeParams) ([]Folder, error)
	ListProjectsByTenant(ctx context.Context, arg ListProjectsByTenantParams) ([]Project, error)
	// ListPrunableVersions returns the versions that fall outside retention, oldest
	// first. Two independent guards keep the current version out of the result: it is
	// excluded by name, and it is always inside the newest-N subquery because it is
	// always the highest version number. Retention pruning that ate the live value
	// would be a catastrophic bug, so it is prevented twice.
	ListPrunableVersions(ctx context.Context, arg ListPrunableVersionsParams) ([]ListPrunableVersionsRow, error)
	ListRootKeys(ctx context.Context) ([]RootKey, error)
	ListRootKeysByState(ctx context.Context, state string) ([]RootKey, error)
	// ListSecretMetaBySubtree is the hierarchical listing: everything at or under a
	// folder path, in one environment, for one tenant.
	//
	// The column list is written out in full rather than `s.*` ON PURPOSE. This query
	// is the one an operator or reviewer reads to confirm that listing cannot leak a
	// value, and an explicit list makes that answerable by inspection — and keeps a
	// future column from joining a list response by accident. (The structural
	// guarantee is stronger still: there is no ciphertext column on secrets to
	// select. Both belts are worn.)
	ListSecretMetaBySubtree(ctx context.Context, arg ListSecretMetaBySubtreeParams) ([]ListSecretMetaBySubtreeRow, error)
	// ListSecretVersionMeta deliberately omits ciphertext, nonce, dek_wrapped and
	// dek_nonce: version history is browsable metadata, not a bulk decryption
	// endpoint. Reading history must never be a way to pull every payload a secret has
	// ever held.
	ListSecretVersionMeta(ctx context.Context, arg ListSecretVersionMetaParams) ([]ListSecretVersionMetaRow, error)
	ListSecretsDueForDestruction(ctx context.Context, limit int32) ([]ListSecretsDueForDestructionRow, error)
	ListTenants(ctx context.Context, arg ListTenantsParams) ([]Tenant, error)
	// ListVersionWrapsByKEK is the rewrap work queue: every version still wrapped
	// under a given root key, oldest row first, in batches. It selects ONLY the
	// wrapping columns — a rewrap never reads or writes ciphertext, which is the
	// entire point of envelope encryption. Ordering by version_id with a limit is what
	// makes the rewrap resumable: a crashed rotation restarts by asking the same
	// question again, and rows already re-wrapped no longer match.
	ListVersionWrapsByKEK(ctx context.Context, arg ListVersionWrapsByKEKParams) ([]ListVersionWrapsByKEKRow, error)
	// The KEK registry. No key material passes through these queries — only the
	// fingerprint that says which key wrapped what.
	// MarkOtherRootKeysRetiring must run BEFORE UpsertActiveRootKey in the same
	// transaction. uq_root_keys_single_active permits exactly one 'active' row, so
	// activating a new key without demoting the old one is a constraint violation, not
	// a silent overwrite. 'retiring' rather than 'retired' because versions still
	// reference the old key until a rewrap completes.
	MarkOtherRootKeysRetiring(ctx context.Context, kekID string) (int64, error)
	// MoveFolderSubtreePaths rewrites the materialized paths of a moved subtree by
	// prefix substitution: everything at or under old_path is re-rooted at new_path.
	// substring(path FROM length(old_path) + 1) is the part of each descendant's path
	// below the moved node, so '/db/primary' under a '/db' -> '/data' move becomes
	// '/data' || '/primary'.
	MoveFolderSubtreePaths(ctx context.Context, arg MoveFolderSubtreePathsParams) (int64, error)
	// RefreshSecretMrnPathsInSubtree recomputes the materialized MRN resource path
	// after a folder move. mrn_resource_path is derived from the environment slug,
	// folder.path and key, so a move that rewrote folder paths leaves it stale — and a
	// stale MRN is an authorization bug, not a display bug, because policy evaluation
	// compares this column. Call it with the subtree's NEW prefix, in the same
	// transaction as the move.
	RefreshSecretMrnPathsInSubtree(ctx context.Context, arg RefreshSecretMrnPathsInSubtreeParams) (int64, error)
	// ReparentFolder moves one folder node: its parent, its name and its own path.
	// The subtree beneath it is rewritten separately by MoveFolderSubtreePaths, and
	// both statements must run in the same transaction or the materialized paths would
	// be observably inconsistent with parent_folder_id.
	ReparentFolder(ctx context.Context, arg ReparentFolderParams) (Folder, error)
	// RestoreSecret can fail with a unique violation on uq_secrets_address: the
	// address is only reserved by LIVE rows, so a new secret may have been created at
	// the same path/key while this one sat deleted. That is a genuine conflict for the
	// caller to resolve, not something to paper over by renaming.
	RestoreSecret(ctx context.Context, arg RestoreSecretParams) (Secret, error)
	// RetireRootKey refuses the active key: `state <> 'active'` is in the WHERE clause,
	// so retiring the key that new writes depend on is not expressible. The caller must
	// also have proved that no version references it (CountVersionsByKEK = 0) —
	// retiring a still-referenced key would leave rows that can never be decrypted.
	RetireRootKey(ctx context.Context, kekID string) (int64, error)
	// RewrapSecretVersion is the ONLY sanctioned UPDATE on this table. It requires the
	// maintainerd.allow_secret_version_rewrap GUC (see AllowSecretVersionRewrap) and
	// the trigger additionally verifies that ciphertext, nonce, version, checksum and
	// created_at came through untouched.
	RewrapSecretVersion(ctx context.Context, arg RewrapSecretVersionParams) (int64, error)
	// SetSecretCurrentVersion publishes a newly written version.
	//
	// current_version only ever moves forward. mark_rotated is false for the very
	// first version (a secret being created has not been "rotated") and true for every
	// version after it — a new value for an existing secret IS a rotation, whether it
	// came from an operator or a rotation job.
	SetSecretCurrentVersion(ctx context.Context, arg SetSecretCurrentVersionParams) (Secret, error)
	SoftDeleteEnvironment(ctx context.Context, arg SoftDeleteEnvironmentParams) (int64, error)
	SoftDeleteFolderSubtree(ctx context.Context, arg SoftDeleteFolderSubtreeParams) (int64, error)
	SoftDeleteProject(ctx context.Context, arg SoftDeleteProjectParams) (int64, error)
	// SoftDeleteSecret starts the recovery window. destroy_after is when the row
	// becomes unrecoverable; until then RestoreSecret puts it back untouched, versions
	// and all.
	SoftDeleteSecret(ctx context.Context, arg SoftDeleteSecretParams) (Secret, error)
	SoftDeleteSecretsInFolderSubtree(ctx context.Context, arg SoftDeleteSecretsInFolderSubtreeParams) (int64, error)
	SoftDeleteTenant(ctx context.Context, tenantUuid uuid.UUID) (int64, error)
	UpdateEnvironment(ctx context.Context, arg UpdateEnvironmentParams) (Environment, error)
	UpdateProject(ctx context.Context, arg UpdateProjectParams) (Project, error)
	UpdateSecretMeta(ctx context.Context, arg UpdateSecretMetaParams) (Secret, error)
	UpdateTenant(ctx context.Context, arg UpdateTenantParams) (Tenant, error)
	UpsertActiveRootKey(ctx context.Context, arg UpsertActiveRootKeyParams) (RootKey, error)
}

var _ Querier = (*Queries)(nil)
