// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: root_key.sql

package storage

import (
	"context"
)

const getActiveRootKey = `-- name: GetActiveRootKey :one
SELECT kek_id, provider, state, created_at, activated_at, retired_at FROM root_keys WHERE state = 'active'
`

func (q *Queries) GetActiveRootKey(ctx context.Context) (RootKey, error) {
	row := q.db.QueryRow(ctx, getActiveRootKey)
	var i RootKey
	err := row.Scan(
		&i.KekID,
		&i.Provider,
		&i.State,
		&i.CreatedAt,
		&i.ActivatedAt,
		&i.RetiredAt,
	)
	return i, err
}

const getRootKey = `-- name: GetRootKey :one
SELECT kek_id, provider, state, created_at, activated_at, retired_at FROM root_keys WHERE kek_id = $1
`

func (q *Queries) GetRootKey(ctx context.Context, kekID string) (RootKey, error) {
	row := q.db.QueryRow(ctx, getRootKey, kekID)
	var i RootKey
	err := row.Scan(
		&i.KekID,
		&i.Provider,
		&i.State,
		&i.CreatedAt,
		&i.ActivatedAt,
		&i.RetiredAt,
	)
	return i, err
}

const listRootKeys = `-- name: ListRootKeys :many
SELECT kek_id, provider, state, created_at, activated_at, retired_at FROM root_keys ORDER BY created_at
`

func (q *Queries) ListRootKeys(ctx context.Context) ([]RootKey, error) {
	rows, err := q.db.Query(ctx, listRootKeys)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RootKey{}
	for rows.Next() {
		var i RootKey
		if err := rows.Scan(
			&i.KekID,
			&i.Provider,
			&i.State,
			&i.CreatedAt,
			&i.ActivatedAt,
			&i.RetiredAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRootKeysByState = `-- name: ListRootKeysByState :many
SELECT kek_id, provider, state, created_at, activated_at, retired_at FROM root_keys WHERE state = $1 ORDER BY created_at
`

func (q *Queries) ListRootKeysByState(ctx context.Context, state string) ([]RootKey, error) {
	rows, err := q.db.Query(ctx, listRootKeysByState, state)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RootKey{}
	for rows.Next() {
		var i RootKey
		if err := rows.Scan(
			&i.KekID,
			&i.Provider,
			&i.State,
			&i.CreatedAt,
			&i.ActivatedAt,
			&i.RetiredAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markOtherRootKeysRetiring = `-- name: MarkOtherRootKeysRetiring :execrows

UPDATE root_keys SET state = 'retiring' WHERE state = 'active' AND kek_id <> $1
`

// The KEK registry. No key material passes through these queries — only the
// fingerprint that says which key wrapped what.
// MarkOtherRootKeysRetiring must run BEFORE UpsertActiveRootKey in the same
// transaction. uq_root_keys_single_active permits exactly one 'active' row, so
// activating a new key without demoting the old one is a constraint violation, not
// a silent overwrite. 'retiring' rather than 'retired' because versions still
// reference the old key until a rewrap completes.
func (q *Queries) MarkOtherRootKeysRetiring(ctx context.Context, kekID string) (int64, error) {
	result, err := q.db.Exec(ctx, markOtherRootKeysRetiring, kekID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const retireRootKey = `-- name: RetireRootKey :execrows
UPDATE root_keys SET state = 'retired', retired_at = now()
WHERE kek_id = $1 AND state <> 'active'
`

// RetireRootKey refuses the active key: `state <> 'active'` is in the WHERE clause,
// so retiring the key that new writes depend on is not expressible. The caller must
// also have proved that no version references it (CountVersionsByKEK = 0) —
// retiring a still-referenced key would leave rows that can never be decrypted.
func (q *Queries) RetireRootKey(ctx context.Context, kekID string) (int64, error) {
	result, err := q.db.Exec(ctx, retireRootKey, kekID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const upsertActiveRootKey = `-- name: UpsertActiveRootKey :one
INSERT INTO root_keys (kek_id, provider, state, activated_at)
VALUES ($1, $2, 'active', now())
ON CONFLICT (kek_id) DO UPDATE
   SET state        = 'active',
       provider     = EXCLUDED.provider,
       activated_at = COALESCE(root_keys.activated_at, now()),
       retired_at   = NULL
RETURNING kek_id, provider, state, created_at, activated_at, retired_at
`

type UpsertActiveRootKeyParams struct {
	KekID    string `json:"kek_id"`
	Provider string `json:"provider"`
}

func (q *Queries) UpsertActiveRootKey(ctx context.Context, arg UpsertActiveRootKeyParams) (RootKey, error) {
	row := q.db.QueryRow(ctx, upsertActiveRootKey, arg.KekID, arg.Provider)
	var i RootKey
	err := row.Scan(
		&i.KekID,
		&i.Provider,
		&i.State,
		&i.CreatedAt,
		&i.ActivatedAt,
		&i.RetiredAt,
	)
	return i, err
}
