// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: scope_import.sql

package storage

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createScopeImport = `-- name: CreateScopeImport :one

INSERT INTO scope_imports (
    tenant_id, environment_id, folder_id,
    source_environment_id, source_folder_id, position, enabled, metadata
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING import_uuid, import_id, tenant_id, environment_id, folder_id, source_environment_id, source_folder_id, position, enabled, metadata, created_at, updated_at, deleted_at
`

type CreateScopeImportParams struct {
	TenantID            int64  `json:"tenant_id"`
	EnvironmentID       int64  `json:"environment_id"`
	FolderID            int64  `json:"folder_id"`
	SourceEnvironmentID int64  `json:"source_environment_id"`
	SourceFolderID      int64  `json:"source_folder_id"`
	Position            int32  `json:"position"`
	Enabled             bool   `json:"enabled"`
	Metadata            []byte `json:"metadata"`
}

// Scope imports: "this folder inherits that folder's secrets".
//
// Tenant scoping is in the WHERE clause of every statement, same rule as the rest
// of this directory. The table carries tenant_id of its own (rather than reaching
// it through folders) precisely so that rule costs nothing here.
func (q *Queries) CreateScopeImport(ctx context.Context, arg CreateScopeImportParams) (ScopeImport, error) {
	row := q.db.QueryRow(ctx, createScopeImport,
		arg.TenantID,
		arg.EnvironmentID,
		arg.FolderID,
		arg.SourceEnvironmentID,
		arg.SourceFolderID,
		arg.Position,
		arg.Enabled,
		arg.Metadata,
	)
	var i ScopeImport
	err := row.Scan(
		&i.ImportUuid,
		&i.ImportID,
		&i.TenantID,
		&i.EnvironmentID,
		&i.FolderID,
		&i.SourceEnvironmentID,
		&i.SourceFolderID,
		&i.Position,
		&i.Enabled,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getScopeImportByUUID = `-- name: GetScopeImportByUUID :one
SELECT import_uuid, import_id, tenant_id, environment_id, folder_id, source_environment_id, source_folder_id, position, enabled, metadata, created_at, updated_at, deleted_at FROM scope_imports
WHERE tenant_id = $1
  AND import_uuid = $2
  AND deleted_at IS NULL
`

type GetScopeImportByUUIDParams struct {
	TenantID   int64     `json:"tenant_id"`
	ImportUuid uuid.UUID `json:"import_uuid"`
}

func (q *Queries) GetScopeImportByUUID(ctx context.Context, arg GetScopeImportByUUIDParams) (ScopeImport, error) {
	row := q.db.QueryRow(ctx, getScopeImportByUUID, arg.TenantID, arg.ImportUuid)
	var i ScopeImport
	err := row.Scan(
		&i.ImportUuid,
		&i.ImportID,
		&i.TenantID,
		&i.EnvironmentID,
		&i.FolderID,
		&i.SourceEnvironmentID,
		&i.SourceFolderID,
		&i.Position,
		&i.Enabled,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listScopeImportsByEnvironment = `-- name: ListScopeImportsByEnvironment :many
SELECT si.import_uuid, si.import_id, si.tenant_id, si.environment_id, si.folder_id, si.source_environment_id, si.source_folder_id, si.position, si.enabled, si.metadata, si.created_at, si.updated_at, si.deleted_at, se.slug AS source_environment_slug, sf.path AS source_folder_path,
       sp.slug AS source_project_slug, tf.path AS folder_path
FROM scope_imports si
JOIN environments se ON se.environment_id = si.source_environment_id
JOIN projects sp ON sp.project_id = se.project_id
JOIN folders sf ON sf.folder_id = si.source_folder_id
JOIN folders tf ON tf.folder_id = si.folder_id
WHERE si.tenant_id = $1
  AND si.environment_id = $2
  AND si.deleted_at IS NULL
ORDER BY tf.path, si.position, si.import_id
`

type ListScopeImportsByEnvironmentParams struct {
	TenantID      int64 `json:"tenant_id"`
	EnvironmentID int64 `json:"environment_id"`
}

type ListScopeImportsByEnvironmentRow struct {
	ImportUuid            uuid.UUID          `json:"import_uuid"`
	ImportID              int64              `json:"import_id"`
	TenantID              int64              `json:"tenant_id"`
	EnvironmentID         int64              `json:"environment_id"`
	FolderID              int64              `json:"folder_id"`
	SourceEnvironmentID   int64              `json:"source_environment_id"`
	SourceFolderID        int64              `json:"source_folder_id"`
	Position              int32              `json:"position"`
	Enabled               bool               `json:"enabled"`
	Metadata              []byte             `json:"metadata"`
	CreatedAt             time.Time          `json:"created_at"`
	UpdatedAt             time.Time          `json:"updated_at"`
	DeletedAt             pgtype.Timestamptz `json:"deleted_at"`
	SourceEnvironmentSlug string             `json:"source_environment_slug"`
	SourceFolderPath      string             `json:"source_folder_path"`
	SourceProjectSlug     string             `json:"source_project_slug"`
	FolderPath            string             `json:"folder_path"`
}

func (q *Queries) ListScopeImportsByEnvironment(ctx context.Context, arg ListScopeImportsByEnvironmentParams) ([]ListScopeImportsByEnvironmentRow, error) {
	rows, err := q.db.Query(ctx, listScopeImportsByEnvironment, arg.TenantID, arg.EnvironmentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListScopeImportsByEnvironmentRow{}
	for rows.Next() {
		var i ListScopeImportsByEnvironmentRow
		if err := rows.Scan(
			&i.ImportUuid,
			&i.ImportID,
			&i.TenantID,
			&i.EnvironmentID,
			&i.FolderID,
			&i.SourceEnvironmentID,
			&i.SourceFolderID,
			&i.Position,
			&i.Enabled,
			&i.Metadata,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.SourceEnvironmentSlug,
			&i.SourceFolderPath,
			&i.SourceProjectSlug,
			&i.FolderPath,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listScopeImportsBySource = `-- name: ListScopeImportsBySource :many
SELECT import_uuid, import_id, tenant_id, environment_id, folder_id, source_environment_id, source_folder_id, position, enabled, metadata, created_at, updated_at, deleted_at FROM scope_imports
WHERE tenant_id = $1
  AND source_folder_id = $2
  AND deleted_at IS NULL
`

type ListScopeImportsBySourceParams struct {
	TenantID       int64 `json:"tenant_id"`
	SourceFolderID int64 `json:"source_folder_id"`
}

// ListScopeImportsBySource answers "what imports me", which is what the cycle
// check walks and what the console shows before letting an operator delete a
// folder other environments depend on.
func (q *Queries) ListScopeImportsBySource(ctx context.Context, arg ListScopeImportsBySourceParams) ([]ScopeImport, error) {
	rows, err := q.db.Query(ctx, listScopeImportsBySource, arg.TenantID, arg.SourceFolderID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ScopeImport{}
	for rows.Next() {
		var i ScopeImport
		if err := rows.Scan(
			&i.ImportUuid,
			&i.ImportID,
			&i.TenantID,
			&i.EnvironmentID,
			&i.FolderID,
			&i.SourceEnvironmentID,
			&i.SourceFolderID,
			&i.Position,
			&i.Enabled,
			&i.Metadata,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listScopeImportsByTarget = `-- name: ListScopeImportsByTarget :many
SELECT si.import_uuid, si.import_id, si.tenant_id, si.environment_id, si.folder_id, si.source_environment_id, si.source_folder_id, si.position, si.enabled, si.metadata, si.created_at, si.updated_at, si.deleted_at, se.slug AS source_environment_slug, sf.path AS source_folder_path,
       sp.slug AS source_project_slug
FROM scope_imports si
JOIN environments se ON se.environment_id = si.source_environment_id
JOIN projects sp ON sp.project_id = se.project_id
JOIN folders sf ON sf.folder_id = si.source_folder_id
WHERE si.tenant_id = $1
  AND si.folder_id = $2
  AND si.deleted_at IS NULL
  AND si.enabled
  AND se.deleted_at IS NULL
  AND sf.deleted_at IS NULL
ORDER BY si.position, si.import_id
`

type ListScopeImportsByTargetParams struct {
	TenantID int64 `json:"tenant_id"`
	FolderID int64 `json:"folder_id"`
}

type ListScopeImportsByTargetRow struct {
	ImportUuid            uuid.UUID          `json:"import_uuid"`
	ImportID              int64              `json:"import_id"`
	TenantID              int64              `json:"tenant_id"`
	EnvironmentID         int64              `json:"environment_id"`
	FolderID              int64              `json:"folder_id"`
	SourceEnvironmentID   int64              `json:"source_environment_id"`
	SourceFolderID        int64              `json:"source_folder_id"`
	Position              int32              `json:"position"`
	Enabled               bool               `json:"enabled"`
	Metadata              []byte             `json:"metadata"`
	CreatedAt             time.Time          `json:"created_at"`
	UpdatedAt             time.Time          `json:"updated_at"`
	DeletedAt             pgtype.Timestamptz `json:"deleted_at"`
	SourceEnvironmentSlug string             `json:"source_environment_slug"`
	SourceFolderPath      string             `json:"source_folder_path"`
	SourceProjectSlug     string             `json:"source_project_slug"`
}

// ListScopeImportsByTarget is the resolver's read: the enabled imports of one
// folder, in precedence order. `position, import_id` rather than `position` alone
// so two imports written at the same position still resolve deterministically —
// a resolution order that varies between replicas would make "which value did we
// get" unanswerable.
func (q *Queries) ListScopeImportsByTarget(ctx context.Context, arg ListScopeImportsByTargetParams) ([]ListScopeImportsByTargetRow, error) {
	rows, err := q.db.Query(ctx, listScopeImportsByTarget, arg.TenantID, arg.FolderID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListScopeImportsByTargetRow{}
	for rows.Next() {
		var i ListScopeImportsByTargetRow
		if err := rows.Scan(
			&i.ImportUuid,
			&i.ImportID,
			&i.TenantID,
			&i.EnvironmentID,
			&i.FolderID,
			&i.SourceEnvironmentID,
			&i.SourceFolderID,
			&i.Position,
			&i.Enabled,
			&i.Metadata,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.SourceEnvironmentSlug,
			&i.SourceFolderPath,
			&i.SourceProjectSlug,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setScopeImportEnabled = `-- name: SetScopeImportEnabled :one
UPDATE scope_imports
SET enabled = $1, position = $2, updated_at = now()
WHERE tenant_id = $3
  AND import_uuid = $4
  AND deleted_at IS NULL
RETURNING import_uuid, import_id, tenant_id, environment_id, folder_id, source_environment_id, source_folder_id, position, enabled, metadata, created_at, updated_at, deleted_at
`

type SetScopeImportEnabledParams struct {
	Enabled    bool      `json:"enabled"`
	Position   int32     `json:"position"`
	TenantID   int64     `json:"tenant_id"`
	ImportUuid uuid.UUID `json:"import_uuid"`
}

func (q *Queries) SetScopeImportEnabled(ctx context.Context, arg SetScopeImportEnabledParams) (ScopeImport, error) {
	row := q.db.QueryRow(ctx, setScopeImportEnabled,
		arg.Enabled,
		arg.Position,
		arg.TenantID,
		arg.ImportUuid,
	)
	var i ScopeImport
	err := row.Scan(
		&i.ImportUuid,
		&i.ImportID,
		&i.TenantID,
		&i.EnvironmentID,
		&i.FolderID,
		&i.SourceEnvironmentID,
		&i.SourceFolderID,
		&i.Position,
		&i.Enabled,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const softDeleteScopeImport = `-- name: SoftDeleteScopeImport :execrows
UPDATE scope_imports SET deleted_at = now(), updated_at = now()
WHERE tenant_id = $1
  AND import_uuid = $2
  AND deleted_at IS NULL
`

type SoftDeleteScopeImportParams struct {
	TenantID   int64     `json:"tenant_id"`
	ImportUuid uuid.UUID `json:"import_uuid"`
}

func (q *Queries) SoftDeleteScopeImport(ctx context.Context, arg SoftDeleteScopeImportParams) (int64, error) {
	result, err := q.db.Exec(ctx, softDeleteScopeImport, arg.TenantID, arg.ImportUuid)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
