// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: secret.sql

package storage

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countSecretsInSubtree = `-- name: CountSecretsInSubtree :one
SELECT count(*)
FROM secrets s
JOIN folders f ON f.folder_id = s.folder_id
WHERE s.tenant_id = $1
  AND s.environment_id = $2
  AND (f.path = $3 OR f.path LIKE $4)
  AND s.deleted_at IS NULL
  AND f.deleted_at IS NULL
`

type CountSecretsInSubtreeParams struct {
	TenantID      int64  `json:"tenant_id"`
	EnvironmentID int64  `json:"environment_id"`
	Path          string `json:"path"`
	PathPattern   string `json:"path_pattern"`
}

func (q *Queries) CountSecretsInSubtree(ctx context.Context, arg CountSecretsInSubtreeParams) (int64, error) {
	row := q.db.QueryRow(ctx, countSecretsInSubtree,
		arg.TenantID,
		arg.EnvironmentID,
		arg.Path,
		arg.PathPattern,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createSecret = `-- name: CreateSecret :one

INSERT INTO secrets (
    tenant_id, project_id, environment_id, folder_id,
    mrn_service, mrn_tenant, mrn_project, mrn_resource_path,
    key, description, tags, keep_versions, rotation_policy, expires_at, metadata
) VALUES (
    $1, $2, $3, $4,
    $5, $6, $7, $8,
    $9, $10, $11, $12, $13, $14, $15
)
RETURNING secret_id, secret_uuid, tenant_id, project_id, environment_id, folder_id, mrn_service, mrn_tenant, mrn_project, mrn_resource_path, key, description, tags, current_version, keep_versions, rotation_policy, rotated_at, expires_at, metadata, created_by, updated_by, created_at, updated_at, deleted_at, destroy_after
`

type CreateSecretParams struct {
	TenantID        int64              `json:"tenant_id"`
	ProjectID       int64              `json:"project_id"`
	EnvironmentID   int64              `json:"environment_id"`
	FolderID        int64              `json:"folder_id"`
	MrnService      string             `json:"mrn_service"`
	MrnTenant       string             `json:"mrn_tenant"`
	MrnProject      string             `json:"mrn_project"`
	MrnResourcePath string             `json:"mrn_resource_path"`
	Key             string             `json:"key"`
	Description     string             `json:"description"`
	Tags            []byte             `json:"tags"`
	KeepVersions    pgtype.Int4        `json:"keep_versions"`
	RotationPolicy  []byte             `json:"rotation_policy"`
	ExpiresAt       pgtype.Timestamptz `json:"expires_at"`
	Metadata        []byte             `json:"metadata"`
}

// Secrets: identity and metadata. NO QUERY IN THIS FILE RETURNS A VALUE, because
// the secrets table has no value column at all — payloads live only in
// secret_versions (see secret_version.sql).
//
// TENANT SCOPING IS IN THE QUERY, NOT IN THE SERVICE. Every statement here
// constrains tenant_id. That is the difference between "we remember to check" and
// "it cannot happen": a service-layer check is one forgotten early-return away
// from leaking, whereas a WHERE clause that is part of the generated function's
// signature cannot be skipped — sqlc will not compile a call that omits the
// parameter. This is also why tenant_id is denormalized onto secrets rather than
// reached by joining up through project and environment.
func (q *Queries) CreateSecret(ctx context.Context, arg CreateSecretParams) (Secret, error) {
	row := q.db.QueryRow(ctx, createSecret,
		arg.TenantID,
		arg.ProjectID,
		arg.EnvironmentID,
		arg.FolderID,
		arg.MrnService,
		arg.MrnTenant,
		arg.MrnProject,
		arg.MrnResourcePath,
		arg.Key,
		arg.Description,
		arg.Tags,
		arg.KeepVersions,
		arg.RotationPolicy,
		arg.ExpiresAt,
		arg.Metadata,
	)
	var i Secret
	err := row.Scan(
		&i.SecretID,
		&i.SecretUuid,
		&i.TenantID,
		&i.ProjectID,
		&i.EnvironmentID,
		&i.FolderID,
		&i.MrnService,
		&i.MrnTenant,
		&i.MrnProject,
		&i.MrnResourcePath,
		&i.Key,
		&i.Description,
		&i.Tags,
		&i.CurrentVersion,
		&i.KeepVersions,
		&i.RotationPolicy,
		&i.RotatedAt,
		&i.ExpiresAt,
		&i.Metadata,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.DestroyAfter,
	)
	return i, err
}

const getDeletedSecretByUUID = `-- name: GetDeletedSecretByUUID :one
SELECT secret_id, secret_uuid, tenant_id, project_id, environment_id, folder_id, mrn_service, mrn_tenant, mrn_project, mrn_resource_path, key, description, tags, current_version, keep_versions, rotation_policy, rotated_at, expires_at, metadata, created_by, updated_by, created_at, updated_at, deleted_at, destroy_after FROM secrets WHERE tenant_id = $1 AND secret_uuid = $2 AND deleted_at IS NOT NULL
`

type GetDeletedSecretByUUIDParams struct {
	TenantID   int64     `json:"tenant_id"`
	SecretUuid uuid.UUID `json:"secret_uuid"`
}

func (q *Queries) GetDeletedSecretByUUID(ctx context.Context, arg GetDeletedSecretByUUIDParams) (Secret, error) {
	row := q.db.QueryRow(ctx, getDeletedSecretByUUID, arg.TenantID, arg.SecretUuid)
	var i Secret
	err := row.Scan(
		&i.SecretID,
		&i.SecretUuid,
		&i.TenantID,
		&i.ProjectID,
		&i.EnvironmentID,
		&i.FolderID,
		&i.MrnService,
		&i.MrnTenant,
		&i.MrnProject,
		&i.MrnResourcePath,
		&i.Key,
		&i.Description,
		&i.Tags,
		&i.CurrentVersion,
		&i.KeepVersions,
		&i.RotationPolicy,
		&i.RotatedAt,
		&i.ExpiresAt,
		&i.Metadata,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.DestroyAfter,
	)
	return i, err
}

const getSecretByAddress = `-- name: GetSecretByAddress :one
SELECT secret_id, secret_uuid, tenant_id, project_id, environment_id, folder_id, mrn_service, mrn_tenant, mrn_project, mrn_resource_path, key, description, tags, current_version, keep_versions, rotation_policy, rotated_at, expires_at, metadata, created_by, updated_by, created_at, updated_at, deleted_at, destroy_after FROM secrets
WHERE tenant_id = $1 AND environment_id = $2 AND folder_id = $3 AND key = $4 AND deleted_at IS NULL
`

type GetSecretByAddressParams struct {
	TenantID      int64  `json:"tenant_id"`
	EnvironmentID int64  `json:"environment_id"`
	FolderID      int64  `json:"folder_id"`
	Key           string `json:"key"`
}

func (q *Queries) GetSecretByAddress(ctx context.Context, arg GetSecretByAddressParams) (Secret, error) {
	row := q.db.QueryRow(ctx, getSecretByAddress,
		arg.TenantID,
		arg.EnvironmentID,
		arg.FolderID,
		arg.Key,
	)
	var i Secret
	err := row.Scan(
		&i.SecretID,
		&i.SecretUuid,
		&i.TenantID,
		&i.ProjectID,
		&i.EnvironmentID,
		&i.FolderID,
		&i.MrnService,
		&i.MrnTenant,
		&i.MrnProject,
		&i.MrnResourcePath,
		&i.Key,
		&i.Description,
		&i.Tags,
		&i.CurrentVersion,
		&i.KeepVersions,
		&i.RotationPolicy,
		&i.RotatedAt,
		&i.ExpiresAt,
		&i.Metadata,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.DestroyAfter,
	)
	return i, err
}

const getSecretByAddressForUpdate = `-- name: GetSecretByAddressForUpdate :one
SELECT secret_id, secret_uuid, tenant_id, project_id, environment_id, folder_id, mrn_service, mrn_tenant, mrn_project, mrn_resource_path, key, description, tags, current_version, keep_versions, rotation_policy, rotated_at, expires_at, metadata, created_by, updated_by, created_at, updated_at, deleted_at, destroy_after FROM secrets
WHERE tenant_id = $1 AND environment_id = $2 AND folder_id = $3 AND key = $4 AND deleted_at IS NULL
FOR UPDATE
`

type GetSecretByAddressForUpdateParams struct {
	TenantID      int64  `json:"tenant_id"`
	EnvironmentID int64  `json:"environment_id"`
	FolderID      int64  `json:"folder_id"`
	Key           string `json:"key"`
}

// GetSecretByAddressForUpdate takes a row lock for the write path. Two concurrent
// writes to one secret must serialize: both would otherwise read the same
// current_version, and the second would collide on uq_secret_versions_secret_version
// (or worse, silently reuse a version number if that index were ever relaxed).
func (q *Queries) GetSecretByAddressForUpdate(ctx context.Context, arg GetSecretByAddressForUpdateParams) (Secret, error) {
	row := q.db.QueryRow(ctx, getSecretByAddressForUpdate,
		arg.TenantID,
		arg.EnvironmentID,
		arg.FolderID,
		arg.Key,
	)
	var i Secret
	err := row.Scan(
		&i.SecretID,
		&i.SecretUuid,
		&i.TenantID,
		&i.ProjectID,
		&i.EnvironmentID,
		&i.FolderID,
		&i.MrnService,
		&i.MrnTenant,
		&i.MrnProject,
		&i.MrnResourcePath,
		&i.Key,
		&i.Description,
		&i.Tags,
		&i.CurrentVersion,
		&i.KeepVersions,
		&i.RotationPolicy,
		&i.RotatedAt,
		&i.ExpiresAt,
		&i.Metadata,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.DestroyAfter,
	)
	return i, err
}

const getSecretByUUID = `-- name: GetSecretByUUID :one
SELECT secret_id, secret_uuid, tenant_id, project_id, environment_id, folder_id, mrn_service, mrn_tenant, mrn_project, mrn_resource_path, key, description, tags, current_version, keep_versions, rotation_policy, rotated_at, expires_at, metadata, created_by, updated_by, created_at, updated_at, deleted_at, destroy_after FROM secrets WHERE tenant_id = $1 AND secret_uuid = $2 AND deleted_at IS NULL
`

type GetSecretByUUIDParams struct {
	TenantID   int64     `json:"tenant_id"`
	SecretUuid uuid.UUID `json:"secret_uuid"`
}

func (q *Queries) GetSecretByUUID(ctx context.Context, arg GetSecretByUUIDParams) (Secret, error) {
	row := q.db.QueryRow(ctx, getSecretByUUID, arg.TenantID, arg.SecretUuid)
	var i Secret
	err := row.Scan(
		&i.SecretID,
		&i.SecretUuid,
		&i.TenantID,
		&i.ProjectID,
		&i.EnvironmentID,
		&i.FolderID,
		&i.MrnService,
		&i.MrnTenant,
		&i.MrnProject,
		&i.MrnResourcePath,
		&i.Key,
		&i.Description,
		&i.Tags,
		&i.CurrentVersion,
		&i.KeepVersions,
		&i.RotationPolicy,
		&i.RotatedAt,
		&i.ExpiresAt,
		&i.Metadata,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.DestroyAfter,
	)
	return i, err
}

const hardDeleteSecret = `-- name: HardDeleteSecret :execrows
DELETE FROM secrets
WHERE tenant_id = $1
  AND secret_uuid = $2
  AND deleted_at IS NOT NULL
  AND destroy_after IS NOT NULL
  AND destroy_after <= now()
`

type HardDeleteSecretParams struct {
	TenantID   int64     `json:"tenant_id"`
	SecretUuid uuid.UUID `json:"secret_uuid"`
}

// HardDeleteSecret is irreversible. The recovery-window guard is IN THE QUERY and
// reads now() from the database rather than trusting a timestamp from the caller:
// destruction inside the window would be unrecoverable data loss, so the check has
// to hold even against a clock-skewed caller or a future code path that forgets
// to look. Cascades into secret_versions, which requires the
// maintainerd.allow_secret_version_delete GUC to be set to 'secret_destroy' in
// the same transaction.
func (q *Queries) HardDeleteSecret(ctx context.Context, arg HardDeleteSecretParams) (int64, error) {
	result, err := q.db.Exec(ctx, hardDeleteSecret, arg.TenantID, arg.SecretUuid)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const listDeletedSecretMeta = `-- name: ListDeletedSecretMeta :many
SELECT
    s.secret_uuid,
    f.path AS folder_path,
    s.key,
    s.current_version,
    s.deleted_at,
    s.destroy_after
FROM secrets s
JOIN folders f ON f.folder_id = s.folder_id
WHERE s.tenant_id = $1
  AND s.environment_id = $2
  AND s.deleted_at IS NOT NULL
ORDER BY s.deleted_at DESC
LIMIT $4 OFFSET $3
`

type ListDeletedSecretMetaParams struct {
	TenantID      int64 `json:"tenant_id"`
	EnvironmentID int64 `json:"environment_id"`
	RowOffset     int32 `json:"row_offset"`
	RowLimit      int32 `json:"row_limit"`
}

type ListDeletedSecretMetaRow struct {
	SecretUuid     uuid.UUID          `json:"secret_uuid"`
	FolderPath     string             `json:"folder_path"`
	Key            string             `json:"key"`
	CurrentVersion int32              `json:"current_version"`
	DeletedAt      pgtype.Timestamptz `json:"deleted_at"`
	DestroyAfter   pgtype.Timestamptz `json:"destroy_after"`
}

// ListDeletedSecretMeta is the recovery-window view: what can still be restored,
// and until when. Metadata only, same rule as the live listing.
func (q *Queries) ListDeletedSecretMeta(ctx context.Context, arg ListDeletedSecretMetaParams) ([]ListDeletedSecretMetaRow, error) {
	rows, err := q.db.Query(ctx, listDeletedSecretMeta,
		arg.TenantID,
		arg.EnvironmentID,
		arg.RowOffset,
		arg.RowLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListDeletedSecretMetaRow{}
	for rows.Next() {
		var i ListDeletedSecretMetaRow
		if err := rows.Scan(
			&i.SecretUuid,
			&i.FolderPath,
			&i.Key,
			&i.CurrentVersion,
			&i.DeletedAt,
			&i.DestroyAfter,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSecretMetaBySubtree = `-- name: ListSecretMetaBySubtree :many
SELECT
    s.secret_uuid,
    f.path AS folder_path,
    s.key,
    s.description,
    s.tags,
    s.current_version,
    s.keep_versions,
    s.rotation_policy,
    s.mrn_tenant,
    s.mrn_project,
    s.mrn_resource_path,
    s.rotated_at,
    s.expires_at,
    s.created_at,
    s.updated_at
FROM secrets s
JOIN folders f ON f.folder_id = s.folder_id
WHERE s.tenant_id = $1
  AND s.environment_id = $2
  AND (f.path = $3 OR f.path LIKE $4)
  AND s.deleted_at IS NULL
  AND f.deleted_at IS NULL
ORDER BY f.path, s.key
LIMIT $6 OFFSET $5
`

type ListSecretMetaBySubtreeParams struct {
	TenantID      int64  `json:"tenant_id"`
	EnvironmentID int64  `json:"environment_id"`
	Path          string `json:"path"`
	PathPattern   string `json:"path_pattern"`
	RowOffset     int32  `json:"row_offset"`
	RowLimit      int32  `json:"row_limit"`
}

type ListSecretMetaBySubtreeRow struct {
	SecretUuid      uuid.UUID          `json:"secret_uuid"`
	FolderPath      string             `json:"folder_path"`
	Key             string             `json:"key"`
	Description     string             `json:"description"`
	Tags            []byte             `json:"tags"`
	CurrentVersion  int32              `json:"current_version"`
	KeepVersions    pgtype.Int4        `json:"keep_versions"`
	RotationPolicy  []byte             `json:"rotation_policy"`
	MrnTenant       string             `json:"mrn_tenant"`
	MrnProject      string             `json:"mrn_project"`
	MrnResourcePath string             `json:"mrn_resource_path"`
	RotatedAt       pgtype.Timestamptz `json:"rotated_at"`
	ExpiresAt       pgtype.Timestamptz `json:"expires_at"`
	CreatedAt       time.Time          `json:"created_at"`
	UpdatedAt       time.Time          `json:"updated_at"`
}

// ListSecretMetaBySubtree is the hierarchical listing: everything at or under a
// folder path, in one environment, for one tenant.
//
// The column list is written out in full rather than `s.*` ON PURPOSE. This query
// is the one an operator or reviewer reads to confirm that listing cannot leak a
// value, and an explicit list makes that answerable by inspection — and keeps a
// future column from joining a list response by accident. (The structural
// guarantee is stronger still: there is no ciphertext column on secrets to
// select. Both belts are worn.)
func (q *Queries) ListSecretMetaBySubtree(ctx context.Context, arg ListSecretMetaBySubtreeParams) ([]ListSecretMetaBySubtreeRow, error) {
	rows, err := q.db.Query(ctx, listSecretMetaBySubtree,
		arg.TenantID,
		arg.EnvironmentID,
		arg.Path,
		arg.PathPattern,
		arg.RowOffset,
		arg.RowLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSecretMetaBySubtreeRow{}
	for rows.Next() {
		var i ListSecretMetaBySubtreeRow
		if err := rows.Scan(
			&i.SecretUuid,
			&i.FolderPath,
			&i.Key,
			&i.Description,
			&i.Tags,
			&i.CurrentVersion,
			&i.KeepVersions,
			&i.RotationPolicy,
			&i.MrnTenant,
			&i.MrnProject,
			&i.MrnResourcePath,
			&i.RotatedAt,
			&i.ExpiresAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSecretsDueForDestruction = `-- name: ListSecretsDueForDestruction :many
SELECT secret_id, secret_uuid, tenant_id, destroy_after FROM secrets
WHERE deleted_at IS NOT NULL AND destroy_after IS NOT NULL AND destroy_after <= now()
ORDER BY destroy_after
LIMIT $1
`

type ListSecretsDueForDestructionRow struct {
	SecretID     int64              `json:"secret_id"`
	SecretUuid   uuid.UUID          `json:"secret_uuid"`
	TenantID     int64              `json:"tenant_id"`
	DestroyAfter pgtype.Timestamptz `json:"destroy_after"`
}

func (q *Queries) ListSecretsDueForDestruction(ctx context.Context, limit int32) ([]ListSecretsDueForDestructionRow, error) {
	rows, err := q.db.Query(ctx, listSecretsDueForDestruction, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSecretsDueForDestructionRow{}
	for rows.Next() {
		var i ListSecretsDueForDestructionRow
		if err := rows.Scan(
			&i.SecretID,
			&i.SecretUuid,
			&i.TenantID,
			&i.DestroyAfter,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSecretsWithRotationPolicy = `-- name: ListSecretsWithRotationPolicy :many
SELECT s.secret_id, s.secret_uuid, t.tenant_uuid, p.slug AS project_slug,
       e.slug AS environment_slug, f.path AS folder_path, s.key,
       s.current_version, s.rotation_policy, s.rotated_at, s.created_at,
       s.mrn_tenant, s.mrn_project, s.mrn_resource_path
FROM secrets s
JOIN tenants t ON t.tenant_id = s.tenant_id
JOIN projects p ON p.project_id = s.project_id
JOIN environments e ON e.environment_id = s.environment_id
JOIN folders f ON f.folder_id = s.folder_id
WHERE s.deleted_at IS NULL
  AND t.deleted_at IS NULL
  AND p.deleted_at IS NULL
  AND e.deleted_at IS NULL
  AND f.deleted_at IS NULL
  AND s.rotation_policy ->> 'enabled' = 'true'
ORDER BY s.secret_id
LIMIT $2 OFFSET $1
`

type ListSecretsWithRotationPolicyParams struct {
	RowOffset int32 `json:"row_offset"`
	RowLimit  int32 `json:"row_limit"`
}

type ListSecretsWithRotationPolicyRow struct {
	SecretID        int64              `json:"secret_id"`
	SecretUuid      uuid.UUID          `json:"secret_uuid"`
	TenantUuid      uuid.UUID          `json:"tenant_uuid"`
	ProjectSlug     string             `json:"project_slug"`
	EnvironmentSlug string             `json:"environment_slug"`
	FolderPath      string             `json:"folder_path"`
	Key             string             `json:"key"`
	CurrentVersion  int32              `json:"current_version"`
	RotationPolicy  []byte             `json:"rotation_policy"`
	RotatedAt       pgtype.Timestamptz `json:"rotated_at"`
	CreatedAt       time.Time          `json:"created_at"`
	MrnTenant       string             `json:"mrn_tenant"`
	MrnProject      string             `json:"mrn_project"`
	MrnResourcePath string             `json:"mrn_resource_path"`
}

// ListSecretsWithRotationPolicy is the background rotator's work queue: every live
// secret whose rotation_policy declares itself enabled, with the addressing columns
// the rotator needs to write a new version.
//
// WHETHER A SECRET IS *DUE* IS DECIDED IN GO, NOT HERE. Expressing "rotated_at +
// interval <= now()" in SQL means parsing a Go duration string inside Postgres, and
// an interval this query mis-parses is either a credential that silently stops
// rotating or one that rotates every tick. The filter that belongs in SQL is the
// cheap, unambiguous one (enabled, live); the arithmetic belongs next to the parser
// that owns the format, where it is unit-testable without a database.
//
// The select list is metadata plus addressing — no ciphertext. The rotator generates
// a NEW value, so it never needs to read the current one.
func (q *Queries) ListSecretsWithRotationPolicy(ctx context.Context, arg ListSecretsWithRotationPolicyParams) ([]ListSecretsWithRotationPolicyRow, error) {
	rows, err := q.db.Query(ctx, listSecretsWithRotationPolicy, arg.RowOffset, arg.RowLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSecretsWithRotationPolicyRow{}
	for rows.Next() {
		var i ListSecretsWithRotationPolicyRow
		if err := rows.Scan(
			&i.SecretID,
			&i.SecretUuid,
			&i.TenantUuid,
			&i.ProjectSlug,
			&i.EnvironmentSlug,
			&i.FolderPath,
			&i.Key,
			&i.CurrentVersion,
			&i.RotationPolicy,
			&i.RotatedAt,
			&i.CreatedAt,
			&i.MrnTenant,
			&i.MrnProject,
			&i.MrnResourcePath,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const refreshSecretMrnPathsInSubtree = `-- name: RefreshSecretMrnPathsInSubtree :execrows
UPDATE secrets s
SET mrn_resource_path = 'secret/' || e.slug || CASE WHEN f.path = '/' THEN '/' ELSE f.path || '/' END || s.key,
    updated_at = now()
FROM folders f, environments e
WHERE f.folder_id = s.folder_id
  AND e.environment_id = s.environment_id
  AND s.tenant_id = $1
  AND s.environment_id = $2
  AND (f.path = $3 OR f.path LIKE $4)
  AND s.deleted_at IS NULL
`

type RefreshSecretMrnPathsInSubtreeParams struct {
	TenantID      int64  `json:"tenant_id"`
	EnvironmentID int64  `json:"environment_id"`
	Path          string `json:"path"`
	PathPattern   string `json:"path_pattern"`
}

// RefreshSecretMrnPathsInSubtree recomputes the materialized MRN resource path
// after a folder move. mrn_resource_path is derived from the environment slug,
// folder.path and key, so a move that rewrote folder paths leaves it stale — and a
// stale MRN is an authorization bug, not a display bug, because policy evaluation
// compares this column. Call it with the subtree's NEW prefix, in the same
// transaction as the move.
func (q *Queries) RefreshSecretMrnPathsInSubtree(ctx context.Context, arg RefreshSecretMrnPathsInSubtreeParams) (int64, error) {
	result, err := q.db.Exec(ctx, refreshSecretMrnPathsInSubtree,
		arg.TenantID,
		arg.EnvironmentID,
		arg.Path,
		arg.PathPattern,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const restoreSecret = `-- name: RestoreSecret :one
UPDATE secrets
SET deleted_at    = NULL,
    destroy_after = NULL,
    updated_at    = now()
WHERE tenant_id = $1 AND secret_uuid = $2 AND deleted_at IS NOT NULL
RETURNING secret_id, secret_uuid, tenant_id, project_id, environment_id, folder_id, mrn_service, mrn_tenant, mrn_project, mrn_resource_path, key, description, tags, current_version, keep_versions, rotation_policy, rotated_at, expires_at, metadata, created_by, updated_by, created_at, updated_at, deleted_at, destroy_after
`

type RestoreSecretParams struct {
	TenantID   int64     `json:"tenant_id"`
	SecretUuid uuid.UUID `json:"secret_uuid"`
}

// RestoreSecret can fail with a unique violation on uq_secrets_address: the
// address is only reserved by LIVE rows, so a new secret may have been created at
// the same path/key while this one sat deleted. That is a genuine conflict for the
// caller to resolve, not something to paper over by renaming.
func (q *Queries) RestoreSecret(ctx context.Context, arg RestoreSecretParams) (Secret, error) {
	row := q.db.QueryRow(ctx, restoreSecret, arg.TenantID, arg.SecretUuid)
	var i Secret
	err := row.Scan(
		&i.SecretID,
		&i.SecretUuid,
		&i.TenantID,
		&i.ProjectID,
		&i.EnvironmentID,
		&i.FolderID,
		&i.MrnService,
		&i.MrnTenant,
		&i.MrnProject,
		&i.MrnResourcePath,
		&i.Key,
		&i.Description,
		&i.Tags,
		&i.CurrentVersion,
		&i.KeepVersions,
		&i.RotationPolicy,
		&i.RotatedAt,
		&i.ExpiresAt,
		&i.Metadata,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.DestroyAfter,
	)
	return i, err
}

const setSecretCurrentVersion = `-- name: SetSecretCurrentVersion :one
UPDATE secrets
SET current_version = $1,
    rotated_at      = CASE WHEN $2::boolean THEN now() ELSE rotated_at END,
    updated_at      = now()
WHERE tenant_id = $3
  AND secret_id = $4
  AND deleted_at IS NULL
  AND current_version < $1
RETURNING secret_id, secret_uuid, tenant_id, project_id, environment_id, folder_id, mrn_service, mrn_tenant, mrn_project, mrn_resource_path, key, description, tags, current_version, keep_versions, rotation_policy, rotated_at, expires_at, metadata, created_by, updated_by, created_at, updated_at, deleted_at, destroy_after
`

type SetSecretCurrentVersionParams struct {
	CurrentVersion int32 `json:"current_version"`
	MarkRotated    bool  `json:"mark_rotated"`
	TenantID       int64 `json:"tenant_id"`
	SecretID       int64 `json:"secret_id"`
}

// SetSecretCurrentVersion publishes a newly written version.
//
// current_version only ever moves forward. mark_rotated is false for the very
// first version (a secret being created has not been "rotated") and true for every
// version after it — a new value for an existing secret IS a rotation, whether it
// came from an operator or a rotation job.
func (q *Queries) SetSecretCurrentVersion(ctx context.Context, arg SetSecretCurrentVersionParams) (Secret, error) {
	row := q.db.QueryRow(ctx, setSecretCurrentVersion,
		arg.CurrentVersion,
		arg.MarkRotated,
		arg.TenantID,
		arg.SecretID,
	)
	var i Secret
	err := row.Scan(
		&i.SecretID,
		&i.SecretUuid,
		&i.TenantID,
		&i.ProjectID,
		&i.EnvironmentID,
		&i.FolderID,
		&i.MrnService,
		&i.MrnTenant,
		&i.MrnProject,
		&i.MrnResourcePath,
		&i.Key,
		&i.Description,
		&i.Tags,
		&i.CurrentVersion,
		&i.KeepVersions,
		&i.RotationPolicy,
		&i.RotatedAt,
		&i.ExpiresAt,
		&i.Metadata,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.DestroyAfter,
	)
	return i, err
}

const softDeleteSecret = `-- name: SoftDeleteSecret :one
UPDATE secrets
SET deleted_at    = now(),
    destroy_after = $1,
    updated_at    = now()
WHERE tenant_id = $2 AND secret_id = $3 AND deleted_at IS NULL
RETURNING secret_id, secret_uuid, tenant_id, project_id, environment_id, folder_id, mrn_service, mrn_tenant, mrn_project, mrn_resource_path, key, description, tags, current_version, keep_versions, rotation_policy, rotated_at, expires_at, metadata, created_by, updated_by, created_at, updated_at, deleted_at, destroy_after
`

type SoftDeleteSecretParams struct {
	DestroyAfter pgtype.Timestamptz `json:"destroy_after"`
	TenantID     int64              `json:"tenant_id"`
	SecretID     int64              `json:"secret_id"`
}

// SoftDeleteSecret starts the recovery window. destroy_after is when the row
// becomes unrecoverable; until then RestoreSecret puts it back untouched, versions
// and all.
func (q *Queries) SoftDeleteSecret(ctx context.Context, arg SoftDeleteSecretParams) (Secret, error) {
	row := q.db.QueryRow(ctx, softDeleteSecret, arg.DestroyAfter, arg.TenantID, arg.SecretID)
	var i Secret
	err := row.Scan(
		&i.SecretID,
		&i.SecretUuid,
		&i.TenantID,
		&i.ProjectID,
		&i.EnvironmentID,
		&i.FolderID,
		&i.MrnService,
		&i.MrnTenant,
		&i.MrnProject,
		&i.MrnResourcePath,
		&i.Key,
		&i.Description,
		&i.Tags,
		&i.CurrentVersion,
		&i.KeepVersions,
		&i.RotationPolicy,
		&i.RotatedAt,
		&i.ExpiresAt,
		&i.Metadata,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.DestroyAfter,
	)
	return i, err
}

const softDeleteSecretsInFolderSubtree = `-- name: SoftDeleteSecretsInFolderSubtree :execrows
UPDATE secrets
SET deleted_at    = now(),
    destroy_after = $1,
    updated_at    = now()
WHERE secrets.tenant_id = $2
  AND secrets.environment_id = $3
  AND secrets.deleted_at IS NULL
  AND secrets.folder_id IN (
      SELECT f.folder_id FROM folders f
      WHERE f.environment_id = $3
        AND (f.path = $4 OR f.path LIKE $5))
`

type SoftDeleteSecretsInFolderSubtreeParams struct {
	DestroyAfter  pgtype.Timestamptz `json:"destroy_after"`
	TenantID      int64              `json:"tenant_id"`
	EnvironmentID int64              `json:"environment_id"`
	Path          string             `json:"path"`
	PathPattern   string             `json:"path_pattern"`
}

func (q *Queries) SoftDeleteSecretsInFolderSubtree(ctx context.Context, arg SoftDeleteSecretsInFolderSubtreeParams) (int64, error) {
	result, err := q.db.Exec(ctx, softDeleteSecretsInFolderSubtree,
		arg.DestroyAfter,
		arg.TenantID,
		arg.EnvironmentID,
		arg.Path,
		arg.PathPattern,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateSecretMeta = `-- name: UpdateSecretMeta :one
UPDATE secrets
SET description     = $1,
    tags            = $2,
    keep_versions   = $3,
    rotation_policy = $4,
    expires_at      = $5,
    metadata        = $6,
    updated_at      = now()
WHERE tenant_id = $7 AND secret_uuid = $8 AND deleted_at IS NULL
RETURNING secret_id, secret_uuid, tenant_id, project_id, environment_id, folder_id, mrn_service, mrn_tenant, mrn_project, mrn_resource_path, key, description, tags, current_version, keep_versions, rotation_policy, rotated_at, expires_at, metadata, created_by, updated_by, created_at, updated_at, deleted_at, destroy_after
`

type UpdateSecretMetaParams struct {
	Description    string             `json:"description"`
	Tags           []byte             `json:"tags"`
	KeepVersions   pgtype.Int4        `json:"keep_versions"`
	RotationPolicy []byte             `json:"rotation_policy"`
	ExpiresAt      pgtype.Timestamptz `json:"expires_at"`
	Metadata       []byte             `json:"metadata"`
	TenantID       int64              `json:"tenant_id"`
	SecretUuid     uuid.UUID          `json:"secret_uuid"`
}

func (q *Queries) UpdateSecretMeta(ctx context.Context, arg UpdateSecretMetaParams) (Secret, error) {
	row := q.db.QueryRow(ctx, updateSecretMeta,
		arg.Description,
		arg.Tags,
		arg.KeepVersions,
		arg.RotationPolicy,
		arg.ExpiresAt,
		arg.Metadata,
		arg.TenantID,
		arg.SecretUuid,
	)
	var i Secret
	err := row.Scan(
		&i.SecretID,
		&i.SecretUuid,
		&i.TenantID,
		&i.ProjectID,
		&i.EnvironmentID,
		&i.FolderID,
		&i.MrnService,
		&i.MrnTenant,
		&i.MrnProject,
		&i.MrnResourcePath,
		&i.Key,
		&i.Description,
		&i.Tags,
		&i.CurrentVersion,
		&i.KeepVersions,
		&i.RotationPolicy,
		&i.RotatedAt,
		&i.ExpiresAt,
		&i.Metadata,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.DestroyAfter,
	)
	return i, err
}
