// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: secret_lease.sql

package storage

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const consumeSecretLease = `-- name: ConsumeSecretLease :execrows
UPDATE secret_leases
SET reads_used   = reads_used + 1,
    last_read_at = now(),
    updated_at   = now()
WHERE lease_id = $1
  AND revoked_at IS NULL
  AND expires_at > now()
  AND (max_reads IS NULL OR reads_used < max_reads)
`

// ConsumeSecretLease records one read against a lease.
//
// THE CAP IS IN THE WHERE CLAUSE, not only in the service. reads_used < max_reads is
// re-checked by the database under the row lock the caller already holds, so a service
// path that forgot to check — or a future second caller of this query — still cannot
// take a read past the limit. Zero rows returned means "refused", and the service maps
// that to the precise error rather than serving the value.
func (q *Queries) ConsumeSecretLease(ctx context.Context, leaseID int64) (int64, error) {
	result, err := q.db.Exec(ctx, consumeSecretLease, leaseID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const countSecretLeases = `-- name: CountSecretLeases :one
SELECT count(*) FROM secret_leases
WHERE tenant_id = $1 AND secret_id = $2
`

type CountSecretLeasesParams struct {
	TenantID int64 `json:"tenant_id"`
	SecretID int64 `json:"secret_id"`
}

func (q *Queries) CountSecretLeases(ctx context.Context, arg CountSecretLeasesParams) (int64, error) {
	row := q.db.QueryRow(ctx, countSecretLeases, arg.TenantID, arg.SecretID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createSecretLease = `-- name: CreateSecretLease :one
INSERT INTO secret_leases (
    tenant_id, secret_id, resource_mrn, requester, requester_kind, expires_at, max_reads
) VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING lease_id, lease_uuid, tenant_id, secret_id, resource_mrn, requester, requester_kind, issued_at, expires_at, max_reads, reads_used, last_read_at, revoked_at, revoke_reason, created_at, updated_at
`

type CreateSecretLeaseParams struct {
	TenantID      int64       `json:"tenant_id"`
	SecretID      int64       `json:"secret_id"`
	ResourceMrn   string      `json:"resource_mrn"`
	Requester     string      `json:"requester"`
	RequesterKind string      `json:"requester_kind"`
	ExpiresAt     time.Time   `json:"expires_at"`
	MaxReads      pgtype.Int4 `json:"max_reads"`
}

func (q *Queries) CreateSecretLease(ctx context.Context, arg CreateSecretLeaseParams) (SecretLease, error) {
	row := q.db.QueryRow(ctx, createSecretLease,
		arg.TenantID,
		arg.SecretID,
		arg.ResourceMrn,
		arg.Requester,
		arg.RequesterKind,
		arg.ExpiresAt,
		arg.MaxReads,
	)
	var i SecretLease
	err := row.Scan(
		&i.LeaseID,
		&i.LeaseUuid,
		&i.TenantID,
		&i.SecretID,
		&i.ResourceMrn,
		&i.Requester,
		&i.RequesterKind,
		&i.IssuedAt,
		&i.ExpiresAt,
		&i.MaxReads,
		&i.ReadsUsed,
		&i.LastReadAt,
		&i.RevokedAt,
		&i.RevokeReason,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const expireDueSecretLeases = `-- name: ExpireDueSecretLeases :execrows
UPDATE secret_leases
SET revoked_at    = now(),
    revoke_reason = 'expired',
    updated_at    = now()
WHERE lease_id IN (
    SELECT lease_id FROM secret_leases
    WHERE revoked_at IS NULL AND expires_at <= now()
    ORDER BY expires_at
    LIMIT $1
)
`

// ExpireDueSecretLeases retires leases whose TTL has run out, in bulk. now() is the
// DATABASE's: a skewed process clock must not be able to expire a lease early or keep
// a dead one alive. This is housekeeping rather than enforcement — the consume path
// already refuses an expired lease on its own — so it is safe to run on a timer and
// safe to skip.
func (q *Queries) ExpireDueSecretLeases(ctx context.Context, rowLimit int32) (int64, error) {
	result, err := q.db.Exec(ctx, expireDueSecretLeases, rowLimit)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getLiveSecretLeaseForUpdate = `-- name: GetLiveSecretLeaseForUpdate :one

SELECT lease_id, lease_uuid, tenant_id, secret_id, resource_mrn, requester, requester_kind, issued_at, expires_at, max_reads, reads_used, last_read_at, revoked_at, revoke_reason, created_at, updated_at FROM secret_leases
WHERE tenant_id = $1
  AND secret_id = $2
  AND requester = $3
  AND revoked_at IS NULL
FOR UPDATE
`

type GetLiveSecretLeaseForUpdateParams struct {
	TenantID  int64  `json:"tenant_id"`
	SecretID  int64  `json:"secret_id"`
	Requester string `json:"requester"`
}

// Read leases on static secrets.
//
// The policy lives on `secrets` (lease_ttl_seconds, lease_max_ttl_seconds,
// lease_max_reads — see secret.sql's SetSecretLeasePolicy); these queries manage the
// leases actually issued against it.
//
// THE CONSUME PATH IS A LOCK, A DECISION, AND AN UPDATE, in that order, inside one
// transaction. Anything looser is a bypass: two concurrent reveals that both read
// reads_used = 9 against a cap of 10 would both be served, which is precisely the
// exfiltration pattern the cap exists to refuse.
// GetLiveSecretLeaseForUpdate takes the caller's current lease under a row lock. NULL
// rows (no lease yet) come back as pgx.ErrNoRows, which the service reads as "issue
// one".
func (q *Queries) GetLiveSecretLeaseForUpdate(ctx context.Context, arg GetLiveSecretLeaseForUpdateParams) (SecretLease, error) {
	row := q.db.QueryRow(ctx, getLiveSecretLeaseForUpdate, arg.TenantID, arg.SecretID, arg.Requester)
	var i SecretLease
	err := row.Scan(
		&i.LeaseID,
		&i.LeaseUuid,
		&i.TenantID,
		&i.SecretID,
		&i.ResourceMrn,
		&i.Requester,
		&i.RequesterKind,
		&i.IssuedAt,
		&i.ExpiresAt,
		&i.MaxReads,
		&i.ReadsUsed,
		&i.LastReadAt,
		&i.RevokedAt,
		&i.RevokeReason,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listSecretLeases = `-- name: ListSecretLeases :many
SELECT lease_uuid, secret_id, resource_mrn, requester, requester_kind,
       issued_at, expires_at, max_reads, reads_used, last_read_at,
       revoked_at, revoke_reason
FROM secret_leases
WHERE tenant_id = $1 AND secret_id = $2
ORDER BY created_at DESC
LIMIT $4 OFFSET $3
`

type ListSecretLeasesParams struct {
	TenantID  int64 `json:"tenant_id"`
	SecretID  int64 `json:"secret_id"`
	RowOffset int32 `json:"row_offset"`
	RowLimit  int32 `json:"row_limit"`
}

type ListSecretLeasesRow struct {
	LeaseUuid     uuid.UUID          `json:"lease_uuid"`
	SecretID      int64              `json:"secret_id"`
	ResourceMrn   string             `json:"resource_mrn"`
	Requester     string             `json:"requester"`
	RequesterKind string             `json:"requester_kind"`
	IssuedAt      time.Time          `json:"issued_at"`
	ExpiresAt     time.Time          `json:"expires_at"`
	MaxReads      pgtype.Int4        `json:"max_reads"`
	ReadsUsed     int32              `json:"reads_used"`
	LastReadAt    pgtype.Timestamptz `json:"last_read_at"`
	RevokedAt     pgtype.Timestamptz `json:"revoked_at"`
	RevokeReason  string             `json:"revoke_reason"`
}

func (q *Queries) ListSecretLeases(ctx context.Context, arg ListSecretLeasesParams) ([]ListSecretLeasesRow, error) {
	rows, err := q.db.Query(ctx, listSecretLeases,
		arg.TenantID,
		arg.SecretID,
		arg.RowOffset,
		arg.RowLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSecretLeasesRow{}
	for rows.Next() {
		var i ListSecretLeasesRow
		if err := rows.Scan(
			&i.LeaseUuid,
			&i.SecretID,
			&i.ResourceMrn,
			&i.Requester,
			&i.RequesterKind,
			&i.IssuedAt,
			&i.ExpiresAt,
			&i.MaxReads,
			&i.ReadsUsed,
			&i.LastReadAt,
			&i.RevokedAt,
			&i.RevokeReason,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeSecretLease = `-- name: RevokeSecretLease :execrows
UPDATE secret_leases
SET revoked_at    = now(),
    revoke_reason = $1,
    updated_at    = now()
WHERE lease_id = $2 AND revoked_at IS NULL
`

type RevokeSecretLeaseParams struct {
	RevokeReason string `json:"revoke_reason"`
	LeaseID      int64  `json:"lease_id"`
}

func (q *Queries) RevokeSecretLease(ctx context.Context, arg RevokeSecretLeaseParams) (int64, error) {
	result, err := q.db.Exec(ctx, revokeSecretLease, arg.RevokeReason, arg.LeaseID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const revokeSecretLeasesForSecret = `-- name: RevokeSecretLeasesForSecret :execrows
UPDATE secret_leases
SET revoked_at    = now(),
    revoke_reason = $1,
    updated_at    = now()
WHERE tenant_id = $2 AND secret_id = $3 AND revoked_at IS NULL
`

type RevokeSecretLeasesForSecretParams struct {
	RevokeReason string `json:"revoke_reason"`
	TenantID     int64  `json:"tenant_id"`
	SecretID     int64  `json:"secret_id"`
}

// RevokeSecretLeasesForSecret closes every outstanding lease on one secret. Used when
// the lease policy is removed (the leases it governed no longer mean anything) and
// when the secret is deleted.
func (q *Queries) RevokeSecretLeasesForSecret(ctx context.Context, arg RevokeSecretLeasesForSecretParams) (int64, error) {
	result, err := q.db.Exec(ctx, revokeSecretLeasesForSecret, arg.RevokeReason, arg.TenantID, arg.SecretID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
