// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: secret_version.sql

package storage

import (
	"context"
	"time"
)

const allowSecretVersionDelete = `-- name: AllowSecretVersionDelete :exec
SELECT set_config('maintainerd.allow_secret_version_delete', $1, true)
`

// AllowSecretVersionDelete sets the transaction-local GUC the append-only trigger
// checks. Valid reasons: 'retention', 'secret_destroy', 'tenant_delete'. is_local
// is true, so the permission dies with the transaction and cannot leak into the
// next statement on a pooled connection — which is exactly why it must be called
// inside an explicit transaction to have any effect at all.
func (q *Queries) AllowSecretVersionDelete(ctx context.Context, setConfig string) error {
	_, err := q.db.Exec(ctx, allowSecretVersionDelete, setConfig)
	return err
}

const allowSecretVersionRewrap = `-- name: AllowSecretVersionRewrap :exec
SELECT set_config('maintainerd.allow_secret_version_rewrap', 'rewrap', true)
`

func (q *Queries) AllowSecretVersionRewrap(ctx context.Context) error {
	_, err := q.db.Exec(ctx, allowSecretVersionRewrap)
	return err
}

const countSecretVersions = `-- name: CountSecretVersions :one
SELECT count(*) FROM secret_versions WHERE secret_id = $1
`

func (q *Queries) CountSecretVersions(ctx context.Context, secretID int64) (int64, error) {
	row := q.db.QueryRow(ctx, countSecretVersions, secretID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countVersionsByKEK = `-- name: CountVersionsByKEK :one
SELECT count(*) FROM secret_versions WHERE kek_id = $1
`

// CountVersionsByKEK is the retirement proof: a root key may only be retired when
// this returns zero.
func (q *Queries) CountVersionsByKEK(ctx context.Context, kekID string) (int64, error) {
	row := q.db.QueryRow(ctx, countVersionsByKEK, kekID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createSecretVersion = `-- name: CreateSecretVersion :one

INSERT INTO secret_versions (secret_id, version, ciphertext, nonce, dek_wrapped, dek_nonce, kek_id, value_type, checksum)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING version_id, secret_id, version, ciphertext, nonce, dek_wrapped, dek_nonce, kek_id, value_type, checksum, created_by, created_at
`

type CreateSecretVersionParams struct {
	SecretID   int64  `json:"secret_id"`
	Version    int32  `json:"version"`
	Ciphertext []byte `json:"ciphertext"`
	Nonce      []byte `json:"nonce"`
	DekWrapped []byte `json:"dek_wrapped"`
	DekNonce   []byte `json:"dek_nonce"`
	KekID      string `json:"kek_id"`
	ValueType  string `json:"value_type"`
	Checksum   []byte `json:"checksum"`
}

// Secret versions: the encrypted payloads.
//
// These are the only queries in the repo that touch ciphertext, and every one of
// them is reached through a secret row that was already resolved tenant-scoped
// (secret.sql). secret_id is therefore a capability: holding one means the tenant
// check has already happened. Versions carry no tenant_id of their own for the
// same reason a bank note carries no account number.
func (q *Queries) CreateSecretVersion(ctx context.Context, arg CreateSecretVersionParams) (SecretVersion, error) {
	row := q.db.QueryRow(ctx, createSecretVersion,
		arg.SecretID,
		arg.Version,
		arg.Ciphertext,
		arg.Nonce,
		arg.DekWrapped,
		arg.DekNonce,
		arg.KekID,
		arg.ValueType,
		arg.Checksum,
	)
	var i SecretVersion
	err := row.Scan(
		&i.VersionID,
		&i.SecretID,
		&i.Version,
		&i.Ciphertext,
		&i.Nonce,
		&i.DekWrapped,
		&i.DekNonce,
		&i.KekID,
		&i.ValueType,
		&i.Checksum,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const deleteSecretVersion = `-- name: DeleteSecretVersion :execrows
DELETE FROM secret_versions WHERE version_id = $1
`

func (q *Queries) DeleteSecretVersion(ctx context.Context, versionID int64) (int64, error) {
	result, err := q.db.Exec(ctx, deleteSecretVersion, versionID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getLatestSecretVersion = `-- name: GetLatestSecretVersion :one
SELECT version_id, secret_id, version, ciphertext, nonce, dek_wrapped, dek_nonce, kek_id, value_type, checksum, created_by, created_at FROM secret_versions WHERE secret_id = $1 ORDER BY version DESC LIMIT 1
`

func (q *Queries) GetLatestSecretVersion(ctx context.Context, secretID int64) (SecretVersion, error) {
	row := q.db.QueryRow(ctx, getLatestSecretVersion, secretID)
	var i SecretVersion
	err := row.Scan(
		&i.VersionID,
		&i.SecretID,
		&i.Version,
		&i.Ciphertext,
		&i.Nonce,
		&i.DekWrapped,
		&i.DekNonce,
		&i.KekID,
		&i.ValueType,
		&i.Checksum,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const getLatestVersionChecksum = `-- name: GetLatestVersionChecksum :one
SELECT version, checksum FROM secret_versions WHERE secret_id = $1 ORDER BY version DESC LIMIT 1
`

type GetLatestVersionChecksumRow struct {
	Version  int32  `json:"version"`
	Checksum []byte `json:"checksum"`
}

// GetLatestVersionChecksum answers "is this write actually a change?" without
// decrypting anything, and without the root key being involved at all. That is the
// whole reason checksum is a stored column.
func (q *Queries) GetLatestVersionChecksum(ctx context.Context, secretID int64) (GetLatestVersionChecksumRow, error) {
	row := q.db.QueryRow(ctx, getLatestVersionChecksum, secretID)
	var i GetLatestVersionChecksumRow
	err := row.Scan(&i.Version, &i.Checksum)
	return i, err
}

const getSecretVersion = `-- name: GetSecretVersion :one
SELECT version_id, secret_id, version, ciphertext, nonce, dek_wrapped, dek_nonce, kek_id, value_type, checksum, created_by, created_at FROM secret_versions WHERE secret_id = $1 AND version = $2
`

type GetSecretVersionParams struct {
	SecretID int64 `json:"secret_id"`
	Version  int32 `json:"version"`
}

func (q *Queries) GetSecretVersion(ctx context.Context, arg GetSecretVersionParams) (SecretVersion, error) {
	row := q.db.QueryRow(ctx, getSecretVersion, arg.SecretID, arg.Version)
	var i SecretVersion
	err := row.Scan(
		&i.VersionID,
		&i.SecretID,
		&i.Version,
		&i.Ciphertext,
		&i.Nonce,
		&i.DekWrapped,
		&i.DekNonce,
		&i.KekID,
		&i.ValueType,
		&i.Checksum,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const getSecretVersionValueType = `-- name: GetSecretVersionValueType :one
SELECT value_type FROM secret_versions WHERE secret_id = $1 AND version = $2
`

type GetSecretVersionValueTypeParams struct {
	SecretID int64 `json:"secret_id"`
	Version  int32 `json:"version"`
}

// GetSecretVersionValueType answers "is this secret a reference or a literal?" for
// ONE secret, which is what the single-secret metadata paths (describe, a metadata
// edit, a restore) need to fill SecretMeta.ValueType. The listing gets the same
// column from its own LATERAL join (secret.sql) so it never runs this per row.
//
// It selects value_type ALONE. A describe that fetched the version row and discarded
// the payload would put ciphertext in a handler's locals for a metadata read, and
// would make the "describe never reaches secret_versions' payload" property something
// a reviewer has to trace rather than read.
func (q *Queries) GetSecretVersionValueType(ctx context.Context, arg GetSecretVersionValueTypeParams) (string, error) {
	row := q.db.QueryRow(ctx, getSecretVersionValueType, arg.SecretID, arg.Version)
	var value_type string
	err := row.Scan(&value_type)
	return value_type, err
}

const listPrunableVersions = `-- name: ListPrunableVersions :many
SELECT v.version_id, v.version FROM secret_versions v
WHERE v.secret_id = $1
  AND v.version <> $2
  AND v.version NOT IN (
      SELECT keep.version FROM secret_versions keep
      WHERE keep.secret_id = $1
      ORDER BY keep.version DESC
      LIMIT $3)
ORDER BY v.version
`

type ListPrunableVersionsParams struct {
	SecretID       int64 `json:"secret_id"`
	CurrentVersion int32 `json:"current_version"`
	KeepVersions   int32 `json:"keep_versions"`
}

type ListPrunableVersionsRow struct {
	VersionID int64 `json:"version_id"`
	Version   int32 `json:"version"`
}

// ListPrunableVersions returns the versions that fall outside retention, oldest
// first. Two independent guards keep the current version out of the result: it is
// excluded by name, and it is always inside the newest-N subquery because it is
// always the highest version number. Retention pruning that ate the live value
// would be a catastrophic bug, so it is prevented twice.
func (q *Queries) ListPrunableVersions(ctx context.Context, arg ListPrunableVersionsParams) ([]ListPrunableVersionsRow, error) {
	rows, err := q.db.Query(ctx, listPrunableVersions, arg.SecretID, arg.CurrentVersion, arg.KeepVersions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPrunableVersionsRow{}
	for rows.Next() {
		var i ListPrunableVersionsRow
		if err := rows.Scan(&i.VersionID, &i.Version); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSecretVersionMeta = `-- name: ListSecretVersionMeta :many
SELECT version_id, secret_id, version, kek_id, value_type, checksum, created_at
FROM secret_versions
WHERE secret_id = $1
ORDER BY version DESC
LIMIT $2 OFFSET $3
`

type ListSecretVersionMetaParams struct {
	SecretID int64 `json:"secret_id"`
	Limit    int32 `json:"limit"`
	Offset   int32 `json:"offset"`
}

type ListSecretVersionMetaRow struct {
	VersionID int64     `json:"version_id"`
	SecretID  int64     `json:"secret_id"`
	Version   int32     `json:"version"`
	KekID     string    `json:"kek_id"`
	ValueType string    `json:"value_type"`
	Checksum  []byte    `json:"checksum"`
	CreatedAt time.Time `json:"created_at"`
}

// ListSecretVersionMeta deliberately omits ciphertext, nonce, dek_wrapped and
// dek_nonce: version history is browsable metadata, not a bulk decryption
// endpoint. Reading history must never be a way to pull every payload a secret has
// ever held.
func (q *Queries) ListSecretVersionMeta(ctx context.Context, arg ListSecretVersionMetaParams) ([]ListSecretVersionMetaRow, error) {
	rows, err := q.db.Query(ctx, listSecretVersionMeta, arg.SecretID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSecretVersionMetaRow{}
	for rows.Next() {
		var i ListSecretVersionMetaRow
		if err := rows.Scan(
			&i.VersionID,
			&i.SecretID,
			&i.Version,
			&i.KekID,
			&i.ValueType,
			&i.Checksum,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listVersionWrapsByKEK = `-- name: ListVersionWrapsByKEK :many
SELECT version_id, kek_id, dek_wrapped, dek_nonce FROM secret_versions
WHERE kek_id = $1
ORDER BY version_id
LIMIT $2
`

type ListVersionWrapsByKEKParams struct {
	KekID string `json:"kek_id"`
	Limit int32  `json:"limit"`
}

type ListVersionWrapsByKEKRow struct {
	VersionID  int64  `json:"version_id"`
	KekID      string `json:"kek_id"`
	DekWrapped []byte `json:"dek_wrapped"`
	DekNonce   []byte `json:"dek_nonce"`
}

// ListVersionWrapsByKEK is the rewrap work queue: every version still wrapped
// under a given root key, oldest row first, in batches. It selects ONLY the
// wrapping columns — a rewrap never reads or writes ciphertext, which is the
// entire point of envelope encryption. Ordering by version_id with a limit is what
// makes the rewrap resumable: a crashed rotation restarts by asking the same
// question again, and rows already re-wrapped no longer match.
func (q *Queries) ListVersionWrapsByKEK(ctx context.Context, arg ListVersionWrapsByKEKParams) ([]ListVersionWrapsByKEKRow, error) {
	rows, err := q.db.Query(ctx, listVersionWrapsByKEK, arg.KekID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListVersionWrapsByKEKRow{}
	for rows.Next() {
		var i ListVersionWrapsByKEKRow
		if err := rows.Scan(
			&i.VersionID,
			&i.KekID,
			&i.DekWrapped,
			&i.DekNonce,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const rewrapSecretVersion = `-- name: RewrapSecretVersion :execrows
UPDATE secret_versions
SET dek_wrapped = $1,
    dek_nonce   = $2,
    kek_id      = $3
WHERE version_id = $4 AND kek_id = $5
`

type RewrapSecretVersionParams struct {
	DekWrapped []byte `json:"dek_wrapped"`
	DekNonce   []byte `json:"dek_nonce"`
	KekID      string `json:"kek_id"`
	VersionID  int64  `json:"version_id"`
	FromKekID  string `json:"from_kek_id"`
}

// RewrapSecretVersion is the ONLY sanctioned UPDATE on this table. It requires the
// maintainerd.allow_secret_version_rewrap GUC (see AllowSecretVersionRewrap) and
// the trigger additionally verifies that ciphertext, nonce, version, checksum and
// created_at came through untouched.
func (q *Queries) RewrapSecretVersion(ctx context.Context, arg RewrapSecretVersionParams) (int64, error) {
	result, err := q.db.Exec(ctx, rewrapSecretVersion,
		arg.DekWrapped,
		arg.DekNonce,
		arg.KekID,
		arg.VersionID,
		arg.FromKekID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
