// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: setup_state.sql

package storage

import (
	"context"
)

const completeSetup = `-- name: CompleteSetup :one
INSERT INTO setup_state (id, completed_at, controller, controller_kind)
VALUES (1, now(), $1, $2)
ON CONFLICT (id) DO UPDATE
   SET completed_at    = now(),
       controller      = $1,
       controller_kind = $2,
       updated_at      = now()
   WHERE setup_state.completed_at IS NULL
RETURNING id, completed_at, controller, controller_kind, metadata, created_at, updated_at
`

type CompleteSetupParams struct {
	Controller     string `json:"controller"`
	ControllerKind string `json:"controller_kind"`
}

// CompleteSetup is the one-shot itself. The `WHERE setup_state.completed_at IS
// NULL` guard on the DO UPDATE branch is what makes it single-use: a second caller
// matches the conflict, fails the guard, updates nothing, and gets NO ROW back —
// which the service reads as "already complete". Two concurrent callers therefore
// cannot both win, because the row lock taken by ON CONFLICT serializes them and
// the loser sees the winner's completed_at.
//
// This is the fix for the prototype's in-memory lock, which reopened the setup
// window on every process restart (and, with an empty bootstrap token, reopened it
// unauthenticated).
func (q *Queries) CompleteSetup(ctx context.Context, arg CompleteSetupParams) (SetupState, error) {
	row := q.db.QueryRow(ctx, completeSetup, arg.Controller, arg.ControllerKind)
	var i SetupState
	err := row.Scan(
		&i.ID,
		&i.CompletedAt,
		&i.Controller,
		&i.ControllerKind,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const ensureSetupState = `-- name: EnsureSetupState :exec

INSERT INTO setup_state (id) VALUES (1) ON CONFLICT (id) DO NOTHING
`

// The durable one-shot setup lock.
func (q *Queries) EnsureSetupState(ctx context.Context) error {
	_, err := q.db.Exec(ctx, ensureSetupState)
	return err
}

const getSetupState = `-- name: GetSetupState :one
SELECT id, completed_at, controller, controller_kind, metadata, created_at, updated_at FROM setup_state WHERE id = 1
`

func (q *Queries) GetSetupState(ctx context.Context) (SetupState, error) {
	row := q.db.QueryRow(ctx, getSetupState)
	var i SetupState
	err := row.Scan(
		&i.ID,
		&i.CompletedAt,
		&i.Controller,
		&i.ControllerKind,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
