// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: tenant.sql

package storage

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countTenants = `-- name: CountTenants :one
SELECT count(*) FROM tenants WHERE deleted_at IS NULL
`

func (q *Queries) CountTenants(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countTenants)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createTenant = `-- name: CreateTenant :one

INSERT INTO tenants (auth_tenant_uuid, name, display_name, status, is_system, metadata)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING tenant_id, tenant_uuid, auth_tenant_uuid, name, display_name, status, is_system, metadata, created_by, updated_by, created_at, updated_at, deleted_at
`

type CreateTenantParams struct {
	AuthTenantUuid pgtype.UUID `json:"auth_tenant_uuid"`
	Name           string      `json:"name"`
	DisplayName    string      `json:"display_name"`
	Status         string      `json:"status"`
	IsSystem       bool        `json:"is_system"`
	Metadata       []byte      `json:"metadata"`
}

// The tenant mirror. Auth owns identity; these rows exist so every secret can be
// keyed to a tenant with one indexed local read instead of a cross-service call.
//
// created_by / updated_by are left to their NULL defaults throughout this file.
// This service has no users table — the authenticated principal is an Auth
// subject string, and it is recorded where it belongs, in audit_log.actor_subject.
// The BIGINT audit columns are kept for schema parity with core.
func (q *Queries) CreateTenant(ctx context.Context, arg CreateTenantParams) (Tenant, error) {
	row := q.db.QueryRow(ctx, createTenant,
		arg.AuthTenantUuid,
		arg.Name,
		arg.DisplayName,
		arg.Status,
		arg.IsSystem,
		arg.Metadata,
	)
	var i Tenant
	err := row.Scan(
		&i.TenantID,
		&i.TenantUuid,
		&i.AuthTenantUuid,
		&i.Name,
		&i.DisplayName,
		&i.Status,
		&i.IsSystem,
		&i.Metadata,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getTenantByAuthTenantUUID = `-- name: GetTenantByAuthTenantUUID :one
SELECT tenant_id, tenant_uuid, auth_tenant_uuid, name, display_name, status, is_system, metadata, created_by, updated_by, created_at, updated_at, deleted_at FROM tenants WHERE auth_tenant_uuid = $1 AND deleted_at IS NULL
`

func (q *Queries) GetTenantByAuthTenantUUID(ctx context.Context, authTenantUuid pgtype.UUID) (Tenant, error) {
	row := q.db.QueryRow(ctx, getTenantByAuthTenantUUID, authTenantUuid)
	var i Tenant
	err := row.Scan(
		&i.TenantID,
		&i.TenantUuid,
		&i.AuthTenantUuid,
		&i.Name,
		&i.DisplayName,
		&i.Status,
		&i.IsSystem,
		&i.Metadata,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getTenantByID = `-- name: GetTenantByID :one
SELECT tenant_id, tenant_uuid, auth_tenant_uuid, name, display_name, status, is_system, metadata, created_by, updated_by, created_at, updated_at, deleted_at FROM tenants WHERE tenant_id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetTenantByID(ctx context.Context, tenantID int64) (Tenant, error) {
	row := q.db.QueryRow(ctx, getTenantByID, tenantID)
	var i Tenant
	err := row.Scan(
		&i.TenantID,
		&i.TenantUuid,
		&i.AuthTenantUuid,
		&i.Name,
		&i.DisplayName,
		&i.Status,
		&i.IsSystem,
		&i.Metadata,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getTenantByName = `-- name: GetTenantByName :one
SELECT tenant_id, tenant_uuid, auth_tenant_uuid, name, display_name, status, is_system, metadata, created_by, updated_by, created_at, updated_at, deleted_at FROM tenants WHERE name = $1 AND deleted_at IS NULL
`

func (q *Queries) GetTenantByName(ctx context.Context, name string) (Tenant, error) {
	row := q.db.QueryRow(ctx, getTenantByName, name)
	var i Tenant
	err := row.Scan(
		&i.TenantID,
		&i.TenantUuid,
		&i.AuthTenantUuid,
		&i.Name,
		&i.DisplayName,
		&i.Status,
		&i.IsSystem,
		&i.Metadata,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getTenantByUUID = `-- name: GetTenantByUUID :one
SELECT tenant_id, tenant_uuid, auth_tenant_uuid, name, display_name, status, is_system, metadata, created_by, updated_by, created_at, updated_at, deleted_at FROM tenants WHERE tenant_uuid = $1 AND deleted_at IS NULL
`

func (q *Queries) GetTenantByUUID(ctx context.Context, tenantUuid uuid.UUID) (Tenant, error) {
	row := q.db.QueryRow(ctx, getTenantByUUID, tenantUuid)
	var i Tenant
	err := row.Scan(
		&i.TenantID,
		&i.TenantUuid,
		&i.AuthTenantUuid,
		&i.Name,
		&i.DisplayName,
		&i.Status,
		&i.IsSystem,
		&i.Metadata,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listTenants = `-- name: ListTenants :many
SELECT tenant_id, tenant_uuid, auth_tenant_uuid, name, display_name, status, is_system, metadata, created_by, updated_by, created_at, updated_at, deleted_at FROM tenants
WHERE deleted_at IS NULL
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type ListTenantsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListTenants(ctx context.Context, arg ListTenantsParams) ([]Tenant, error) {
	rows, err := q.db.Query(ctx, listTenants, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Tenant{}
	for rows.Next() {
		var i Tenant
		if err := rows.Scan(
			&i.TenantID,
			&i.TenantUuid,
			&i.AuthTenantUuid,
			&i.Name,
			&i.DisplayName,
			&i.Status,
			&i.IsSystem,
			&i.Metadata,
			&i.CreatedBy,
			&i.UpdatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteTenant = `-- name: SoftDeleteTenant :execrows
UPDATE tenants SET deleted_at = now(), updated_at = now()
WHERE tenant_uuid = $1 AND deleted_at IS NULL
`

func (q *Queries) SoftDeleteTenant(ctx context.Context, tenantUuid uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, softDeleteTenant, tenantUuid)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateTenant = `-- name: UpdateTenant :one
UPDATE tenants
SET display_name = $1,
    status       = $2,
    metadata     = $3,
    updated_at   = now()
WHERE tenant_uuid = $4 AND deleted_at IS NULL
RETURNING tenant_id, tenant_uuid, auth_tenant_uuid, name, display_name, status, is_system, metadata, created_by, updated_by, created_at, updated_at, deleted_at
`

type UpdateTenantParams struct {
	DisplayName string    `json:"display_name"`
	Status      string    `json:"status"`
	Metadata    []byte    `json:"metadata"`
	TenantUuid  uuid.UUID `json:"tenant_uuid"`
}

func (q *Queries) UpdateTenant(ctx context.Context, arg UpdateTenantParams) (Tenant, error) {
	row := q.db.QueryRow(ctx, updateTenant,
		arg.DisplayName,
		arg.Status,
		arg.Metadata,
		arg.TenantUuid,
	)
	var i Tenant
	err := row.Scan(
		&i.TenantID,
		&i.TenantUuid,
		&i.AuthTenantUuid,
		&i.Name,
		&i.DisplayName,
		&i.Status,
		&i.IsSystem,
		&i.Metadata,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
