// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: transit.sql

package storage

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const allowTransitVersionDelete = `-- name: AllowTransitVersionDelete :exec
SELECT set_config('maintainerd.allow_transit_version_delete', $1, true)
`

func (q *Queries) AllowTransitVersionDelete(ctx context.Context, setConfig string) error {
	_, err := q.db.Exec(ctx, allowTransitVersionDelete, setConfig)
	return err
}

const allowTransitVersionRewrap = `-- name: AllowTransitVersionRewrap :exec
SELECT set_config('maintainerd.allow_transit_version_rewrap', 'rewrap', true)
`

// AllowTransitVersionRewrap sets the transaction-local GUC the append-only trigger
// checks. is_local is true, so the permission dies with the transaction and cannot
// leak into the next statement on a pooled connection — which is why it only has any
// effect inside an explicit transaction.
func (q *Queries) AllowTransitVersionRewrap(ctx context.Context) error {
	_, err := q.db.Exec(ctx, allowTransitVersionRewrap)
	return err
}

const countTransitKeyVersions = `-- name: CountTransitKeyVersions :one
SELECT count(*) FROM transit_key_versions WHERE key_id = $1
`

func (q *Queries) CountTransitKeyVersions(ctx context.Context, keyID int64) (int64, error) {
	row := q.db.QueryRow(ctx, countTransitKeyVersions, keyID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countTransitKeysByProject = `-- name: CountTransitKeysByProject :one
SELECT count(*) FROM transit_keys
WHERE tenant_id = $1 AND project_id = $2 AND deleted_at IS NULL
`

type CountTransitKeysByProjectParams struct {
	TenantID  int64 `json:"tenant_id"`
	ProjectID int64 `json:"project_id"`
}

func (q *Queries) CountTransitKeysByProject(ctx context.Context, arg CountTransitKeysByProjectParams) (int64, error) {
	row := q.db.QueryRow(ctx, countTransitKeysByProject, arg.TenantID, arg.ProjectID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countTransitVersionsByKEK = `-- name: CountTransitVersionsByKEK :one
SELECT count(*) FROM transit_key_versions WHERE kek_id = $1
`

// CountTransitVersionsByKEK is half of the retirement proof. A root key may only be
// retired when NO secret version AND no transit key version references it; retiring
// one that a transit version still points at would make that key's ciphertexts
// permanently undecryptable while every secret read kept working, which is the worst
// kind of partial failure — invisible until the application needs its data.
func (q *Queries) CountTransitVersionsByKEK(ctx context.Context, kekID string) (int64, error) {
	row := q.db.QueryRow(ctx, countTransitVersionsByKEK, kekID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createTransitKey = `-- name: CreateTransitKey :one

INSERT INTO transit_keys (
    tenant_id, project_id, name, description, status, min_decrypt_version, metadata
) VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING key_id, key_uuid, tenant_id, project_id, name, description, current_version, status, min_decrypt_version, metadata, created_at, updated_at, deleted_at
`

type CreateTransitKeyParams struct {
	TenantID          int64  `json:"tenant_id"`
	ProjectID         int64  `json:"project_id"`
	Name              string `json:"name"`
	Description       string `json:"description"`
	Status            string `json:"status"`
	MinDecryptVersion int32  `json:"min_decrypt_version"`
	Metadata          []byte `json:"metadata"`
}

// Transit keys and their versions.
//
// THE MATERIAL COLUMNS ARE SELECTED BY EXACTLY TWO QUERIES — the one that resolves
// the version an Encrypt writes under, and the one that resolves the version a
// Decrypt token names. Every listing and every metadata read goes through a *Meta
// shape that does not select them at all, the same belt-and-braces rule the secret
// listing and the webhook listing follow. A transit key's whole value proposition is
// that the material never leaves the service; a listing query that selected it would
// be one JSON marshal away from ending that.
func (q *Queries) CreateTransitKey(ctx context.Context, arg CreateTransitKeyParams) (TransitKey, error) {
	row := q.db.QueryRow(ctx, createTransitKey,
		arg.TenantID,
		arg.ProjectID,
		arg.Name,
		arg.Description,
		arg.Status,
		arg.MinDecryptVersion,
		arg.Metadata,
	)
	var i TransitKey
	err := row.Scan(
		&i.KeyID,
		&i.KeyUuid,
		&i.TenantID,
		&i.ProjectID,
		&i.Name,
		&i.Description,
		&i.CurrentVersion,
		&i.Status,
		&i.MinDecryptVersion,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const createTransitKeyVersion = `-- name: CreateTransitKeyVersion :one
INSERT INTO transit_key_versions (
    key_id, version, material_ciphertext, material_nonce,
    material_dek_wrapped, material_dek_nonce, kek_id
) VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING version_id, key_id, version, material_ciphertext, material_nonce, material_dek_wrapped, material_dek_nonce, kek_id, created_at
`

type CreateTransitKeyVersionParams struct {
	KeyID              int64  `json:"key_id"`
	Version            int32  `json:"version"`
	MaterialCiphertext []byte `json:"material_ciphertext"`
	MaterialNonce      []byte `json:"material_nonce"`
	MaterialDekWrapped []byte `json:"material_dek_wrapped"`
	MaterialDekNonce   []byte `json:"material_dek_nonce"`
	KekID              string `json:"kek_id"`
}

func (q *Queries) CreateTransitKeyVersion(ctx context.Context, arg CreateTransitKeyVersionParams) (TransitKeyVersion, error) {
	row := q.db.QueryRow(ctx, createTransitKeyVersion,
		arg.KeyID,
		arg.Version,
		arg.MaterialCiphertext,
		arg.MaterialNonce,
		arg.MaterialDekWrapped,
		arg.MaterialDekNonce,
		arg.KekID,
	)
	var i TransitKeyVersion
	err := row.Scan(
		&i.VersionID,
		&i.KeyID,
		&i.Version,
		&i.MaterialCiphertext,
		&i.MaterialNonce,
		&i.MaterialDekWrapped,
		&i.MaterialDekNonce,
		&i.KekID,
		&i.CreatedAt,
	)
	return i, err
}

const getLatestTransitKeyVersion = `-- name: GetLatestTransitKeyVersion :one
SELECT version_id, key_id, version, material_ciphertext, material_nonce, material_dek_wrapped, material_dek_nonce, kek_id, created_at FROM transit_key_versions WHERE key_id = $1 ORDER BY version DESC LIMIT 1
`

func (q *Queries) GetLatestTransitKeyVersion(ctx context.Context, keyID int64) (TransitKeyVersion, error) {
	row := q.db.QueryRow(ctx, getLatestTransitKeyVersion, keyID)
	var i TransitKeyVersion
	err := row.Scan(
		&i.VersionID,
		&i.KeyID,
		&i.Version,
		&i.MaterialCiphertext,
		&i.MaterialNonce,
		&i.MaterialDekWrapped,
		&i.MaterialDekNonce,
		&i.KekID,
		&i.CreatedAt,
	)
	return i, err
}

const getTransitKeyByName = `-- name: GetTransitKeyByName :one
SELECT key_id, key_uuid, tenant_id, project_id, name, description, current_version, status, min_decrypt_version, metadata, created_at, updated_at, deleted_at FROM transit_keys
WHERE tenant_id = $1
  AND project_id = $2
  AND name = $3
  AND deleted_at IS NULL
`

type GetTransitKeyByNameParams struct {
	TenantID  int64  `json:"tenant_id"`
	ProjectID int64  `json:"project_id"`
	Name      string `json:"name"`
}

func (q *Queries) GetTransitKeyByName(ctx context.Context, arg GetTransitKeyByNameParams) (TransitKey, error) {
	row := q.db.QueryRow(ctx, getTransitKeyByName, arg.TenantID, arg.ProjectID, arg.Name)
	var i TransitKey
	err := row.Scan(
		&i.KeyID,
		&i.KeyUuid,
		&i.TenantID,
		&i.ProjectID,
		&i.Name,
		&i.Description,
		&i.CurrentVersion,
		&i.Status,
		&i.MinDecryptVersion,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getTransitKeyByNameForUpdate = `-- name: GetTransitKeyByNameForUpdate :one
SELECT key_id, key_uuid, tenant_id, project_id, name, description, current_version, status, min_decrypt_version, metadata, created_at, updated_at, deleted_at FROM transit_keys
WHERE tenant_id = $1
  AND project_id = $2
  AND name = $3
  AND deleted_at IS NULL
FOR UPDATE
`

type GetTransitKeyByNameForUpdateParams struct {
	TenantID  int64  `json:"tenant_id"`
	ProjectID int64  `json:"project_id"`
	Name      string `json:"name"`
}

// GetTransitKeyByNameForUpdate takes a row lock for the rotate path. Two concurrent
// rotations would otherwise both read the same current_version and the second would
// collide on uq_transit_key_versions_key_version — the same race
// GetSecretByAddressForUpdate exists to serialize.
func (q *Queries) GetTransitKeyByNameForUpdate(ctx context.Context, arg GetTransitKeyByNameForUpdateParams) (TransitKey, error) {
	row := q.db.QueryRow(ctx, getTransitKeyByNameForUpdate, arg.TenantID, arg.ProjectID, arg.Name)
	var i TransitKey
	err := row.Scan(
		&i.KeyID,
		&i.KeyUuid,
		&i.TenantID,
		&i.ProjectID,
		&i.Name,
		&i.Description,
		&i.CurrentVersion,
		&i.Status,
		&i.MinDecryptVersion,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getTransitKeyVersion = `-- name: GetTransitKeyVersion :one
SELECT version_id, key_id, version, material_ciphertext, material_nonce, material_dek_wrapped, material_dek_nonce, kek_id, created_at FROM transit_key_versions WHERE key_id = $1 AND version = $2
`

type GetTransitKeyVersionParams struct {
	KeyID   int64 `json:"key_id"`
	Version int32 `json:"version"`
}

// GetTransitKeyVersion is one of the two queries that select material. It takes an
// explicit version because a DECRYPT must open the version the TOKEN names, not the
// current one — that is the whole reason a token carries its key version.
func (q *Queries) GetTransitKeyVersion(ctx context.Context, arg GetTransitKeyVersionParams) (TransitKeyVersion, error) {
	row := q.db.QueryRow(ctx, getTransitKeyVersion, arg.KeyID, arg.Version)
	var i TransitKeyVersion
	err := row.Scan(
		&i.VersionID,
		&i.KeyID,
		&i.Version,
		&i.MaterialCiphertext,
		&i.MaterialNonce,
		&i.MaterialDekWrapped,
		&i.MaterialDekNonce,
		&i.KekID,
		&i.CreatedAt,
	)
	return i, err
}

const listTransitKeyMetaByProject = `-- name: ListTransitKeyMetaByProject :many
SELECT key_uuid, project_id, name, description, current_version, status,
       min_decrypt_version, created_at, updated_at
FROM transit_keys
WHERE tenant_id = $1
  AND project_id = $2
  AND deleted_at IS NULL
ORDER BY name
LIMIT $4 OFFSET $3
`

type ListTransitKeyMetaByProjectParams struct {
	TenantID  int64 `json:"tenant_id"`
	ProjectID int64 `json:"project_id"`
	RowOffset int32 `json:"row_offset"`
	RowLimit  int32 `json:"row_limit"`
}

type ListTransitKeyMetaByProjectRow struct {
	KeyUuid           uuid.UUID `json:"key_uuid"`
	ProjectID         int64     `json:"project_id"`
	Name              string    `json:"name"`
	Description       string    `json:"description"`
	CurrentVersion    int32     `json:"current_version"`
	Status            string    `json:"status"`
	MinDecryptVersion int32     `json:"min_decrypt_version"`
	CreatedAt         time.Time `json:"created_at"`
	UpdatedAt         time.Time `json:"updated_at"`
}

func (q *Queries) ListTransitKeyMetaByProject(ctx context.Context, arg ListTransitKeyMetaByProjectParams) ([]ListTransitKeyMetaByProjectRow, error) {
	rows, err := q.db.Query(ctx, listTransitKeyMetaByProject,
		arg.TenantID,
		arg.ProjectID,
		arg.RowOffset,
		arg.RowLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTransitKeyMetaByProjectRow{}
	for rows.Next() {
		var i ListTransitKeyMetaByProjectRow
		if err := rows.Scan(
			&i.KeyUuid,
			&i.ProjectID,
			&i.Name,
			&i.Description,
			&i.CurrentVersion,
			&i.Status,
			&i.MinDecryptVersion,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTransitKeyVersionMeta = `-- name: ListTransitKeyVersionMeta :many
SELECT version_id, key_id, version, kek_id, created_at
FROM transit_key_versions
WHERE key_id = $1
ORDER BY version DESC
LIMIT $2 OFFSET $3
`

type ListTransitKeyVersionMetaParams struct {
	KeyID  int64 `json:"key_id"`
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

type ListTransitKeyVersionMetaRow struct {
	VersionID int64     `json:"version_id"`
	KeyID     int64     `json:"key_id"`
	Version   int32     `json:"version"`
	KekID     string    `json:"kek_id"`
	CreatedAt time.Time `json:"created_at"`
}

// ListTransitKeyVersionMeta omits every material column: version history is
// browsable metadata, never a way to enumerate key material.
func (q *Queries) ListTransitKeyVersionMeta(ctx context.Context, arg ListTransitKeyVersionMetaParams) ([]ListTransitKeyVersionMetaRow, error) {
	rows, err := q.db.Query(ctx, listTransitKeyVersionMeta, arg.KeyID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTransitKeyVersionMetaRow{}
	for rows.Next() {
		var i ListTransitKeyVersionMetaRow
		if err := rows.Scan(
			&i.VersionID,
			&i.KeyID,
			&i.Version,
			&i.KekID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTransitVersionWrapsByKEK = `-- name: ListTransitVersionWrapsByKEK :many
SELECT version_id, kek_id, material_dek_wrapped, material_dek_nonce
FROM transit_key_versions
WHERE kek_id = $1
ORDER BY version_id
LIMIT $2
`

type ListTransitVersionWrapsByKEKParams struct {
	KekID string `json:"kek_id"`
	Limit int32  `json:"limit"`
}

type ListTransitVersionWrapsByKEKRow struct {
	VersionID          int64  `json:"version_id"`
	KekID              string `json:"kek_id"`
	MaterialDekWrapped []byte `json:"material_dek_wrapped"`
	MaterialDekNonce   []byte `json:"material_dek_nonce"`
}

// ListTransitVersionWrapsByKEK is the rewrap work queue, the transit twin of
// ListVersionWrapsByKEK. It selects ONLY the wrapping columns — a rewrap never reads
// key material, which is the entire point of wrapping it in the first place.
func (q *Queries) ListTransitVersionWrapsByKEK(ctx context.Context, arg ListTransitVersionWrapsByKEKParams) ([]ListTransitVersionWrapsByKEKRow, error) {
	rows, err := q.db.Query(ctx, listTransitVersionWrapsByKEK, arg.KekID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTransitVersionWrapsByKEKRow{}
	for rows.Next() {
		var i ListTransitVersionWrapsByKEKRow
		if err := rows.Scan(
			&i.VersionID,
			&i.KekID,
			&i.MaterialDekWrapped,
			&i.MaterialDekNonce,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const rewrapTransitKeyVersion = `-- name: RewrapTransitKeyVersion :execrows
UPDATE transit_key_versions
SET material_dek_wrapped = $1,
    material_dek_nonce   = $2,
    kek_id               = $3
WHERE version_id = $4 AND kek_id = $5
`

type RewrapTransitKeyVersionParams struct {
	MaterialDekWrapped []byte `json:"material_dek_wrapped"`
	MaterialDekNonce   []byte `json:"material_dek_nonce"`
	KekID              string `json:"kek_id"`
	VersionID          int64  `json:"version_id"`
	FromKekID          string `json:"from_kek_id"`
}

// RewrapTransitKeyVersion is the ONLY sanctioned UPDATE on this table. It requires the
// maintainerd.allow_transit_version_rewrap GUC and the trigger additionally verifies
// that the material ciphertext, nonce, version and created_at came through untouched.
func (q *Queries) RewrapTransitKeyVersion(ctx context.Context, arg RewrapTransitKeyVersionParams) (int64, error) {
	result, err := q.db.Exec(ctx, rewrapTransitKeyVersion,
		arg.MaterialDekWrapped,
		arg.MaterialDekNonce,
		arg.KekID,
		arg.VersionID,
		arg.FromKekID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const setTransitKeyCurrentVersion = `-- name: SetTransitKeyCurrentVersion :one
UPDATE transit_keys
SET current_version = $1,
    updated_at      = now()
WHERE tenant_id = $2
  AND key_id = $3
  AND deleted_at IS NULL
  AND current_version < $1
RETURNING key_id, key_uuid, tenant_id, project_id, name, description, current_version, status, min_decrypt_version, metadata, created_at, updated_at, deleted_at
`

type SetTransitKeyCurrentVersionParams struct {
	CurrentVersion int32 `json:"current_version"`
	TenantID       int64 `json:"tenant_id"`
	KeyID          int64 `json:"key_id"`
}

// SetTransitKeyCurrentVersion publishes a newly created key version. current_version
// only ever moves forward, for the reason secrets.current_version does: a version
// number that could be reused would make a stored token ambiguous.
func (q *Queries) SetTransitKeyCurrentVersion(ctx context.Context, arg SetTransitKeyCurrentVersionParams) (TransitKey, error) {
	row := q.db.QueryRow(ctx, setTransitKeyCurrentVersion, arg.CurrentVersion, arg.TenantID, arg.KeyID)
	var i TransitKey
	err := row.Scan(
		&i.KeyID,
		&i.KeyUuid,
		&i.TenantID,
		&i.ProjectID,
		&i.Name,
		&i.Description,
		&i.CurrentVersion,
		&i.Status,
		&i.MinDecryptVersion,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const softDeleteTransitKey = `-- name: SoftDeleteTransitKey :execrows
UPDATE transit_keys SET deleted_at = now(), updated_at = now()
WHERE tenant_id = $1
  AND key_uuid = $2
  AND deleted_at IS NULL
`

type SoftDeleteTransitKeyParams struct {
	TenantID int64     `json:"tenant_id"`
	KeyUuid  uuid.UUID `json:"key_uuid"`
}

func (q *Queries) SoftDeleteTransitKey(ctx context.Context, arg SoftDeleteTransitKeyParams) (int64, error) {
	result, err := q.db.Exec(ctx, softDeleteTransitKey, arg.TenantID, arg.KeyUuid)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateTransitKey = `-- name: UpdateTransitKey :one
UPDATE transit_keys
SET description         = $1,
    status              = $2,
    min_decrypt_version = $3,
    updated_at          = now()
WHERE tenant_id = $4
  AND key_uuid = $5
  AND deleted_at IS NULL
RETURNING key_id, key_uuid, tenant_id, project_id, name, description, current_version, status, min_decrypt_version, metadata, created_at, updated_at, deleted_at
`

type UpdateTransitKeyParams struct {
	Description       string    `json:"description"`
	Status            string    `json:"status"`
	MinDecryptVersion int32     `json:"min_decrypt_version"`
	TenantID          int64     `json:"tenant_id"`
	KeyUuid           uuid.UUID `json:"key_uuid"`
}

func (q *Queries) UpdateTransitKey(ctx context.Context, arg UpdateTransitKeyParams) (TransitKey, error) {
	row := q.db.QueryRow(ctx, updateTransitKey,
		arg.Description,
		arg.Status,
		arg.MinDecryptVersion,
		arg.TenantID,
		arg.KeyUuid,
	)
	var i TransitKey
	err := row.Scan(
		&i.KeyID,
		&i.KeyUuid,
		&i.TenantID,
		&i.ProjectID,
		&i.Name,
		&i.Description,
		&i.CurrentVersion,
		&i.Status,
		&i.MinDecryptVersion,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
