// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: webhook.sql

package storage

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countWebhookDeliveriesByEndpoint = `-- name: CountWebhookDeliveriesByEndpoint :one
SELECT count(*) FROM webhook_deliveries
WHERE tenant_id = $1 AND endpoint_id = $2
`

type CountWebhookDeliveriesByEndpointParams struct {
	TenantID   int64 `json:"tenant_id"`
	EndpointID int64 `json:"endpoint_id"`
}

func (q *Queries) CountWebhookDeliveriesByEndpoint(ctx context.Context, arg CountWebhookDeliveriesByEndpointParams) (int64, error) {
	row := q.db.QueryRow(ctx, countWebhookDeliveriesByEndpoint, arg.TenantID, arg.EndpointID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countWebhookEndpointsByProject = `-- name: CountWebhookEndpointsByProject :one
SELECT count(*) FROM webhook_endpoints
WHERE tenant_id = $1 AND project_id = $2 AND deleted_at IS NULL
`

type CountWebhookEndpointsByProjectParams struct {
	TenantID  int64 `json:"tenant_id"`
	ProjectID int64 `json:"project_id"`
}

func (q *Queries) CountWebhookEndpointsByProject(ctx context.Context, arg CountWebhookEndpointsByProjectParams) (int64, error) {
	row := q.db.QueryRow(ctx, countWebhookEndpointsByProject, arg.TenantID, arg.ProjectID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createWebhookDelivery = `-- name: CreateWebhookDelivery :one
INSERT INTO webhook_deliveries (
    endpoint_id, tenant_id, event_type, resource_mrn, version, payload
) VALUES ($1, $2, $3, $4, $5, $6)
RETURNING delivery_id, delivery_uuid, endpoint_id, tenant_id, event_type, resource_mrn, version, attempt_count, status, response_status, error, payload, created_at, updated_at
`

type CreateWebhookDeliveryParams struct {
	EndpointID  int64       `json:"endpoint_id"`
	TenantID    int64       `json:"tenant_id"`
	EventType   string      `json:"event_type"`
	ResourceMrn string      `json:"resource_mrn"`
	Version     pgtype.Int4 `json:"version"`
	Payload     []byte      `json:"payload"`
}

func (q *Queries) CreateWebhookDelivery(ctx context.Context, arg CreateWebhookDeliveryParams) (WebhookDelivery, error) {
	row := q.db.QueryRow(ctx, createWebhookDelivery,
		arg.EndpointID,
		arg.TenantID,
		arg.EventType,
		arg.ResourceMrn,
		arg.Version,
		arg.Payload,
	)
	var i WebhookDelivery
	err := row.Scan(
		&i.DeliveryID,
		&i.DeliveryUuid,
		&i.EndpointID,
		&i.TenantID,
		&i.EventType,
		&i.ResourceMrn,
		&i.Version,
		&i.AttemptCount,
		&i.Status,
		&i.ResponseStatus,
		&i.Error,
		&i.Payload,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createWebhookEndpoint = `-- name: CreateWebhookEndpoint :one

INSERT INTO webhook_endpoints (
    endpoint_uuid, tenant_id, project_id, url, description,
    secret_ciphertext, secret_nonce, secret_dek_wrapped, secret_dek_nonce, kek_id,
    events, status, timeout_seconds, max_attempts, metadata
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15)
RETURNING endpoint_id, endpoint_uuid, tenant_id, project_id, url, description, secret_ciphertext, secret_nonce, secret_dek_wrapped, secret_dek_nonce, kek_id, events, status, timeout_seconds, max_attempts, last_triggered_at, metadata, created_at, updated_at, deleted_at
`

type CreateWebhookEndpointParams struct {
	EndpointUuid     uuid.UUID `json:"endpoint_uuid"`
	TenantID         int64     `json:"tenant_id"`
	ProjectID        int64     `json:"project_id"`
	Url              string    `json:"url"`
	Description      string    `json:"description"`
	SecretCiphertext []byte    `json:"secret_ciphertext"`
	SecretNonce      []byte    `json:"secret_nonce"`
	SecretDekWrapped []byte    `json:"secret_dek_wrapped"`
	SecretDekNonce   []byte    `json:"secret_dek_nonce"`
	KekID            string    `json:"kek_id"`
	Events           []byte    `json:"events"`
	Status           string    `json:"status"`
	TimeoutSeconds   int32     `json:"timeout_seconds"`
	MaxAttempts      int32     `json:"max_attempts"`
	Metadata         []byte    `json:"metadata"`
}

// Webhook endpoints and their delivery log.
//
// The signing-key columns are selected explicitly nowhere except the two reads
// that actually need to sign a delivery. Everything a console or an API response
// renders goes through the *Meta shapes below, which do not select the key at all —
// the same belt-and-braces rule the secret listing follows.
// CreateWebhookEndpoint takes endpoint_uuid from the CALLER rather than letting the
// column default supply it. That is not a style preference: the signing key is
// sealed with the endpoint's UUID bound in as additional authenticated data (so a
// ciphertext moved between endpoint rows fails to open), and AAD has to be known
// before the seal — which is before the INSERT. A DB-generated UUID would force
// either an insert-then-update dance or an AAD that binds nothing row-specific.
func (q *Queries) CreateWebhookEndpoint(ctx context.Context, arg CreateWebhookEndpointParams) (WebhookEndpoint, error) {
	row := q.db.QueryRow(ctx, createWebhookEndpoint,
		arg.EndpointUuid,
		arg.TenantID,
		arg.ProjectID,
		arg.Url,
		arg.Description,
		arg.SecretCiphertext,
		arg.SecretNonce,
		arg.SecretDekWrapped,
		arg.SecretDekNonce,
		arg.KekID,
		arg.Events,
		arg.Status,
		arg.TimeoutSeconds,
		arg.MaxAttempts,
		arg.Metadata,
	)
	var i WebhookEndpoint
	err := row.Scan(
		&i.EndpointID,
		&i.EndpointUuid,
		&i.TenantID,
		&i.ProjectID,
		&i.Url,
		&i.Description,
		&i.SecretCiphertext,
		&i.SecretNonce,
		&i.SecretDekWrapped,
		&i.SecretDekNonce,
		&i.KekID,
		&i.Events,
		&i.Status,
		&i.TimeoutSeconds,
		&i.MaxAttempts,
		&i.LastTriggeredAt,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const finishWebhookDelivery = `-- name: FinishWebhookDelivery :one
UPDATE webhook_deliveries
SET attempt_count   = $1,
    status          = $2,
    response_status = $3,
    error           = $4,
    updated_at      = now()
WHERE delivery_id = $5
RETURNING delivery_id, delivery_uuid, endpoint_id, tenant_id, event_type, resource_mrn, version, attempt_count, status, response_status, error, payload, created_at, updated_at
`

type FinishWebhookDeliveryParams struct {
	AttemptCount   int32       `json:"attempt_count"`
	Status         string      `json:"status"`
	ResponseStatus pgtype.Int4 `json:"response_status"`
	Error          string      `json:"error"`
	DeliveryID     int64       `json:"delivery_id"`
}

func (q *Queries) FinishWebhookDelivery(ctx context.Context, arg FinishWebhookDeliveryParams) (WebhookDelivery, error) {
	row := q.db.QueryRow(ctx, finishWebhookDelivery,
		arg.AttemptCount,
		arg.Status,
		arg.ResponseStatus,
		arg.Error,
		arg.DeliveryID,
	)
	var i WebhookDelivery
	err := row.Scan(
		&i.DeliveryID,
		&i.DeliveryUuid,
		&i.EndpointID,
		&i.TenantID,
		&i.EventType,
		&i.ResourceMrn,
		&i.Version,
		&i.AttemptCount,
		&i.Status,
		&i.ResponseStatus,
		&i.Error,
		&i.Payload,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getWebhookEndpointByUUID = `-- name: GetWebhookEndpointByUUID :one
SELECT endpoint_id, endpoint_uuid, tenant_id, project_id, url, description, secret_ciphertext, secret_nonce, secret_dek_wrapped, secret_dek_nonce, kek_id, events, status, timeout_seconds, max_attempts, last_triggered_at, metadata, created_at, updated_at, deleted_at FROM webhook_endpoints
WHERE tenant_id = $1
  AND endpoint_uuid = $2
  AND deleted_at IS NULL
`

type GetWebhookEndpointByUUIDParams struct {
	TenantID     int64     `json:"tenant_id"`
	EndpointUuid uuid.UUID `json:"endpoint_uuid"`
}

func (q *Queries) GetWebhookEndpointByUUID(ctx context.Context, arg GetWebhookEndpointByUUIDParams) (WebhookEndpoint, error) {
	row := q.db.QueryRow(ctx, getWebhookEndpointByUUID, arg.TenantID, arg.EndpointUuid)
	var i WebhookEndpoint
	err := row.Scan(
		&i.EndpointID,
		&i.EndpointUuid,
		&i.TenantID,
		&i.ProjectID,
		&i.Url,
		&i.Description,
		&i.SecretCiphertext,
		&i.SecretNonce,
		&i.SecretDekWrapped,
		&i.SecretDekNonce,
		&i.KekID,
		&i.Events,
		&i.Status,
		&i.TimeoutSeconds,
		&i.MaxAttempts,
		&i.LastTriggeredAt,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listActiveWebhookEndpointsByProject = `-- name: ListActiveWebhookEndpointsByProject :many
SELECT endpoint_id, endpoint_uuid, tenant_id, project_id, url, description, secret_ciphertext, secret_nonce, secret_dek_wrapped, secret_dek_nonce, kek_id, events, status, timeout_seconds, max_attempts, last_triggered_at, metadata, created_at, updated_at, deleted_at FROM webhook_endpoints
WHERE tenant_id = $1
  AND project_id = $2
  AND deleted_at IS NULL
  AND status = 'active'
ORDER BY endpoint_id
`

type ListActiveWebhookEndpointsByProjectParams struct {
	TenantID  int64 `json:"tenant_id"`
	ProjectID int64 `json:"project_id"`
}

// ListActiveWebhookEndpointsByProject IS the delivery read, so it does select the
// wrapped signing key — the notifier needs it to compute the HMAC.
func (q *Queries) ListActiveWebhookEndpointsByProject(ctx context.Context, arg ListActiveWebhookEndpointsByProjectParams) ([]WebhookEndpoint, error) {
	rows, err := q.db.Query(ctx, listActiveWebhookEndpointsByProject, arg.TenantID, arg.ProjectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []WebhookEndpoint{}
	for rows.Next() {
		var i WebhookEndpoint
		if err := rows.Scan(
			&i.EndpointID,
			&i.EndpointUuid,
			&i.TenantID,
			&i.ProjectID,
			&i.Url,
			&i.Description,
			&i.SecretCiphertext,
			&i.SecretNonce,
			&i.SecretDekWrapped,
			&i.SecretDekNonce,
			&i.KekID,
			&i.Events,
			&i.Status,
			&i.TimeoutSeconds,
			&i.MaxAttempts,
			&i.LastTriggeredAt,
			&i.Metadata,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWebhookDeliveriesByEndpoint = `-- name: ListWebhookDeliveriesByEndpoint :many
SELECT delivery_id, delivery_uuid, endpoint_id, tenant_id, event_type, resource_mrn, version, attempt_count, status, response_status, error, payload, created_at, updated_at FROM webhook_deliveries
WHERE tenant_id = $1
  AND endpoint_id = $2
ORDER BY created_at DESC
LIMIT $4 OFFSET $3
`

type ListWebhookDeliveriesByEndpointParams struct {
	TenantID   int64 `json:"tenant_id"`
	EndpointID int64 `json:"endpoint_id"`
	RowOffset  int32 `json:"row_offset"`
	RowLimit   int32 `json:"row_limit"`
}

func (q *Queries) ListWebhookDeliveriesByEndpoint(ctx context.Context, arg ListWebhookDeliveriesByEndpointParams) ([]WebhookDelivery, error) {
	rows, err := q.db.Query(ctx, listWebhookDeliveriesByEndpoint,
		arg.TenantID,
		arg.EndpointID,
		arg.RowOffset,
		arg.RowLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []WebhookDelivery{}
	for rows.Next() {
		var i WebhookDelivery
		if err := rows.Scan(
			&i.DeliveryID,
			&i.DeliveryUuid,
			&i.EndpointID,
			&i.TenantID,
			&i.EventType,
			&i.ResourceMrn,
			&i.Version,
			&i.AttemptCount,
			&i.Status,
			&i.ResponseStatus,
			&i.Error,
			&i.Payload,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWebhookEndpointMetaByProject = `-- name: ListWebhookEndpointMetaByProject :many
SELECT endpoint_uuid, project_id, url, description, events, status,
       timeout_seconds, max_attempts, last_triggered_at, created_at, updated_at
FROM webhook_endpoints
WHERE tenant_id = $1
  AND project_id = $2
  AND deleted_at IS NULL
ORDER BY created_at
LIMIT $4 OFFSET $3
`

type ListWebhookEndpointMetaByProjectParams struct {
	TenantID  int64 `json:"tenant_id"`
	ProjectID int64 `json:"project_id"`
	RowOffset int32 `json:"row_offset"`
	RowLimit  int32 `json:"row_limit"`
}

type ListWebhookEndpointMetaByProjectRow struct {
	EndpointUuid    uuid.UUID          `json:"endpoint_uuid"`
	ProjectID       int64              `json:"project_id"`
	Url             string             `json:"url"`
	Description     string             `json:"description"`
	Events          []byte             `json:"events"`
	Status          string             `json:"status"`
	TimeoutSeconds  int32              `json:"timeout_seconds"`
	MaxAttempts     int32              `json:"max_attempts"`
	LastTriggeredAt pgtype.Timestamptz `json:"last_triggered_at"`
	CreatedAt       time.Time          `json:"created_at"`
	UpdatedAt       time.Time          `json:"updated_at"`
}

// ListWebhookEndpointMetaByProject is the API/console read. The select list omits
// every signing-key column: an endpoint listing must never be a way to obtain the
// key that authenticates deliveries to that endpoint.
func (q *Queries) ListWebhookEndpointMetaByProject(ctx context.Context, arg ListWebhookEndpointMetaByProjectParams) ([]ListWebhookEndpointMetaByProjectRow, error) {
	rows, err := q.db.Query(ctx, listWebhookEndpointMetaByProject,
		arg.TenantID,
		arg.ProjectID,
		arg.RowOffset,
		arg.RowLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListWebhookEndpointMetaByProjectRow{}
	for rows.Next() {
		var i ListWebhookEndpointMetaByProjectRow
		if err := rows.Scan(
			&i.EndpointUuid,
			&i.ProjectID,
			&i.Url,
			&i.Description,
			&i.Events,
			&i.Status,
			&i.TimeoutSeconds,
			&i.MaxAttempts,
			&i.LastTriggeredAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteWebhookEndpoint = `-- name: SoftDeleteWebhookEndpoint :execrows
UPDATE webhook_endpoints SET deleted_at = now(), updated_at = now()
WHERE tenant_id = $1
  AND endpoint_uuid = $2
  AND deleted_at IS NULL
`

type SoftDeleteWebhookEndpointParams struct {
	TenantID     int64     `json:"tenant_id"`
	EndpointUuid uuid.UUID `json:"endpoint_uuid"`
}

func (q *Queries) SoftDeleteWebhookEndpoint(ctx context.Context, arg SoftDeleteWebhookEndpointParams) (int64, error) {
	result, err := q.db.Exec(ctx, softDeleteWebhookEndpoint, arg.TenantID, arg.EndpointUuid)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const touchWebhookEndpoint = `-- name: TouchWebhookEndpoint :execrows
UPDATE webhook_endpoints SET last_triggered_at = now(), updated_at = now()
WHERE endpoint_id = $1
`

func (q *Queries) TouchWebhookEndpoint(ctx context.Context, endpointID int64) (int64, error) {
	result, err := q.db.Exec(ctx, touchWebhookEndpoint, endpointID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateWebhookEndpoint = `-- name: UpdateWebhookEndpoint :one
UPDATE webhook_endpoints
SET url             = $1,
    description     = $2,
    events          = $3,
    status          = $4,
    timeout_seconds = $5,
    max_attempts    = $6,
    updated_at      = now()
WHERE tenant_id = $7
  AND endpoint_uuid = $8
  AND deleted_at IS NULL
RETURNING endpoint_id, endpoint_uuid, tenant_id, project_id, url, description, secret_ciphertext, secret_nonce, secret_dek_wrapped, secret_dek_nonce, kek_id, events, status, timeout_seconds, max_attempts, last_triggered_at, metadata, created_at, updated_at, deleted_at
`

type UpdateWebhookEndpointParams struct {
	Url            string    `json:"url"`
	Description    string    `json:"description"`
	Events         []byte    `json:"events"`
	Status         string    `json:"status"`
	TimeoutSeconds int32     `json:"timeout_seconds"`
	MaxAttempts    int32     `json:"max_attempts"`
	TenantID       int64     `json:"tenant_id"`
	EndpointUuid   uuid.UUID `json:"endpoint_uuid"`
}

func (q *Queries) UpdateWebhookEndpoint(ctx context.Context, arg UpdateWebhookEndpointParams) (WebhookEndpoint, error) {
	row := q.db.QueryRow(ctx, updateWebhookEndpoint,
		arg.Url,
		arg.Description,
		arg.Events,
		arg.Status,
		arg.TimeoutSeconds,
		arg.MaxAttempts,
		arg.TenantID,
		arg.EndpointUuid,
	)
	var i WebhookEndpoint
	err := row.Scan(
		&i.EndpointID,
		&i.EndpointUuid,
		&i.TenantID,
		&i.ProjectID,
		&i.Url,
		&i.Description,
		&i.SecretCiphertext,
		&i.SecretNonce,
		&i.SecretDekWrapped,
		&i.SecretDekNonce,
		&i.KekID,
		&i.Events,
		&i.Status,
		&i.TimeoutSeconds,
		&i.MaxAttempts,
		&i.LastTriggeredAt,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
